### ISSUE TITLE
Cannot unselect an image once selected/set

### ISSUE THREAD

**Issue by IBNobody** [PhilipK/BoilR#100]
Running 1.2.3

Had a case today where I needed to get rid of the logo I had selected because it showed up on the Hero image.

![image](https://user-images.githubusercontent.com/5863888/165413325-608758b0-f622-4530-8acd-d4b6844589f0.png)

However, I cannot unselect that image....

![image](https://user-images.githubusercontent.com/5863888/165414007-3c16650c-4a88-431b-b5b3-7561604bd036.png)

**Comment by PhilipK** [comment]
This is implemented in the newest version (click an image and then pick the "clear image" option)

**Comment by IBNobody** [comment]
While I can clear an image, updating the Steam Library does not clear the image...

Start

![image](https://user-images.githubusercontent.com/5863888/165859497-0310066b-872f-487a-b277-3ea618d21491.png)

Close Steam, Select Images, Select Moonlight

![image](https://user-images.githubusercontent.com/5863888/165859556-a6389dc8-2cc8-4620-80ae-2ea5849bfdae.png)

Select Logo, Click Clear

![image](https://user-images.githubusercontent.com/5863888/165859581-40b72ffb-b182-4478-9340-d8b0730cb98e.png)

Logo Cleared

![image](https://user-images.githubusercontent.com/5863888/165859609-cb65dd81-6e6e-40e3-bd87-7ac0b09e7e8c.png)

Import, Wait for Done

![image](https://user-images.githubusercontent.com/5863888/165859702-7f018a9d-cbd9-45f6-80bc-ae29a4bc337f.png)

Open Steam... No Change :(

![image](https://user-images.githubusercontent.com/5863888/165859724-dd6ce72f-148c-4586-aecc-3584a345fbdb.png)

**Comment by PhilipK** [comment]
Oh, I see the problem.
It clears the image, but then the next time it imports it downloads a new image again.
I guess I need to ban BoilR from downloading a new image when it imports, if you have specifically cleared the image yourself.

**Comment by IBNobody** [comment]
Yes. Do you want me to open a new issue for this for tracking?

**Comment by PhilipK** [comment]
Yes, thanks.
I will look at it the as soon as possible then.
