### ISSUE TITLE
Update Images for already installed Steam Games

### ISSUE THREAD

**Issue by NightHammer1000** [PhilipK/BoilR#102]
Some Games on Steam do not have Stock Big Picture Versions.
These can be pulled form SteamGridDB.

Would be nice if BoilR could do that.

**Comment by isopix** [comment]
So true.

F*** codemasters removed all descriptions and graphics from pulled
games from stores (like GRID: Race Driver (2008), and I've installed
it from store on SteamDeck, I got blank icon, desc and all other
graphics...it looks very sad.

**Comment by PhilipK** [comment]
This would require BoilR to find games that are installed by steam, instead of just the ones in the shortcuts.
Anyone know of a way to reliably do that?

**Comment by NightHammer1000** [comment]
Each installed Game has a appmanifest_<APPID>.acf File in the steamapps folder of the Steam Library.

The content looks like this:

`"AppState"
{
	"appid"		"228980"
	"Universe"		"1"
	"LauncherPath"		"C:\\Program Files (x86)\\Steam\\steam.exe"
	"name"		"Steamworks Common Redistributables"
	"StateFlags"		"1026"
	"installdir"		"Steamworks Shared"
	"LastUpdated"		"0"
	"UpdateResult"		"0"
	"SizeOnDisk"		"0"
	"buildid"		"0"
	"LastOwner"		"76561198031545777"
	"BytesToDownload"		"91877024"
	"BytesDownloaded"		"0"
	"BytesToStage"		"106131471"
	"BytesStaged"		"0"
	"AutoUpdateBehavior"		"0"
	"AllowOtherDownloadsWhileRunning"		"0"
	"ScheduledAutoUpdate"		"0"
	"InstalledDepots"
	{
	}
	"UserConfig"
	{
		"betakey"		"public"
	}
}
`
Should contain everything needed for Matching and Pulling of Artwork.
Artwork for Steam Installed Games can be saved like the ones for Non-Steam Shortcuts.
If I remember right you just save the Imagefile with the SteamID as a filename in the Grid folder under the userdata.

**Comment by PhilipK** [comment]
Perfect.
The app id and the game name is all I need.
Should be easy enough to implement.
Probably will make it a toggle to also see steam games. But once I have the app id, the rest of the system should be the same.

**Comment by NightHammer1000** [comment]
Does BoilR also pull Icons for Steam Desktop Mode?

**Comment by PhilipK** [comment]
From the official steam store assets , yes.
But i don't think it is possible to change icons for steam installed games.

**Comment by NightHammer1000** [comment]
Oh I see.
Should be Possible to get Icons form SteamGridDB as well.
They are usally much nicer. 
I use them with Playnite on my Windows PC all the Time.
Woulld be nice for Non-Steam Games tho.

**Comment by PhilipK** [comment]
This is solved in realse v.1.3.3
