### ISSUE TITLE
Allow Icons to be changed/cleared

### ISSUE THREAD

**Issue by IBNobody** [PhilipK/BoilR#108]
Not sure if this is a bug or intended, but I cannot change the icon of Moonlight Game Streaming. It's stuck on thinking it is the game Moonlight.

![image](https://user-images.githubusercontent.com/5863888/166109045-7c5b041e-69c9-4377-a795-c3ed04f0ce51.png)

I can mouse over and click on the icon, but nothing happens.

I also don't know where the icon is being used. I thought it was being used in the library list, but that's not the case...

![image](https://user-images.githubusercontent.com/5863888/166109094-b1aae14c-bc60-42b1-b5da-9e33e1bf4112.png)

**Comment by XargonWan** [comment]
My Lutris games are without icons when I import them in Steam, maybe an icon scraping can be good.

**Comment by NightHammer1000** [comment]
Icons can be pulled from SteamGridDB.
There is a part of the API for that.

**Comment by PhilipK** [comment]
Just check, and yes, it seems to have been added now. I will get on it asap.
It is one of those things I can actually fix without having a steam deck on hand.

**Comment by NightHammer1000** [comment]
Valve need to send this man a Deck already ^^

**Comment by PhilipK** [comment]
It seems that the newest version has been uploaded to flathub now, I am going to close this.
If it for some reason does not work for you, please let me know and I will reopen the issue.
