### ISSUE TITLE
Automatic catagory assigning

### ISSUE THREAD

**Issue by SjorsMaster** [PhilipK/BoilR#11]
Not sure if this would even be possible, but it could be very useful to put "epic games" in a steam library catagory named "epic" automagically!

**Comment by ffMathy** [comment]
Perhaps https://en.wikipedia.org/wiki/Levenshtein_distance could be used for this? :shrug:

**Comment by PhilipK** [comment]
So one category for epic games, one for origin and so on? And then add those games in there?

**Comment by SjorsMaster** [comment]
> So one category for epic games, one for origin and so on? And then add those games in there?

Indeed, it would help differentiating which game belongs to which platform if you own them on both platforms. I suppose it would work too if the platform name was in the shortcut name, but a catagory would allow for filtering. Not sure if you can set those up though outside of steam itself!

**Comment by PhilipK** [comment]
Good idea. Unfortunately I have not been able to find where steam stores the information about which games go into categories. If I find it I will gladly add this as a feature (maybe optional).

**Comment by PhilipK** [comment]
It turns out that steam rom manager is able to do this, so it should be possible, just have to look at what they do.

**Comment by PhilipK** [comment]
I have been trying to get this to work for a while now:
https://github.com/PhilipK/BoilR/tree/steam-categories

But some times it just randomly crashes after steam edits the file.
I am going to put it on the backburner for a while and focus on some of the bugs that people have been reporting.

**Comment by PhilipK** [comment]
This feature is now in this release:
https://github.com/PhilipK/BoilR/releases/tag/v.0.9.17
