### ISSUE TITLE
Boilr Flathub Not Creating Collections

### ISSUE THREAD

**Issue by kuynh** [PhilipK/BoilR#118]
A pretty small issue but with the Boilr from Flathub, it seems to have trouble creating the collections for the Itch.io games or heroic games.

**Comment by PhilipK** [comment]
Unfortunatly this is a more generic problem where some times it just will not create collections:
https://github.com/PhilipK/BoilR/issues/71

I still have not found a pattern of why it happens.

**Comment by PhilipK** [comment]
I will close this issue since it is a douplicate of https://github.com/PhilipK/BoilR/issues/71 but please post any update you find to this issue there.
