### ISSUE TITLE
Games on Steam Deck SD card are not found

### ISSUE THREAD

**Issue by probablyVincentIp** [PhilipK/BoilR#119]
Using the Steam Deck and Heroic launcher, I am not able to find any games which are installed on the SD card. If the games are moved to the internal storage, it works without any issues.

**Comment by rkr87** [comment]
Download FlatSeal from Discover and give both Boilr and Heroic access to your SD directory, you'll find it in /run/media/.

**Comment by probablyVincentIp** [comment]
@rkr87 Boilr and Heroic both already had access to the sdcard (boilr just read only though). Giving both r/w access still doesn't show anything in Boilr. Is there anything else I am missing?

**Comment by PhilipK** [comment]
Have you tried to run the "non-flatpak" version of BoilR ?
If not, could you see if that can find them? If so, then we know for sure its a flatpak/permissions issue.

This will be easier to fix once I get my steam deck, a week or so I hope.

**Comment by gazpachoking** [comment]
I had this same issue, and adding the sd card to the permissions via flatseal worked. I was fooled at first into thinking it was already there, but `~/run/media/mmcblk0p1` was there rather than `/run/media/mmcblk0p1`

**Comment by PhilipK** [comment]
@gazpachoking I think you found the bug there.
Just checked and yes, the folder name started with ~ which is wrong.
I have just pushed a fix where I remove the ~.
It takes a couple of hours for flathub to update, but this should be fixed soon.
Until then flatseal is your friend, remove the ~ and you are good.

**Comment by PhilipK** [comment]
New release out v.1.3.4 , it should fix this problem.
Remember that flathub takes a while to update after i trigger an update.
Let me know if it doesn't work and I will update this issue.
