### ISSUE TITLE
Searching for game images does not complete

### ISSUE THREAD

**Issue by deltoran0** [PhilipK/BoilR#12]
Firstly thanks for creating such a great application 

Using GUI version and it never seems to complete.
If I click on the GUI once it begins it locks up

> Found 5 user(s)
Found 69 shortcuts for user: C:\Program Files (x86)\Steam\userdata\311838003
Error getting shortcuts from platform: Legendary
The system cannot find the file specified. (os error 2)
Found 40 game(s) for platform Origin
Found 1 game(s) for platform Gog
Saved 69 shortcuts
Finished synchronizing games in: 43.2475ms
Found 69 shortcuts for user: C:\Program Files (x86)\Steam\userdata\53868787
Error getting shortcuts from platform: Legendary
The system cannot find the file specified. (os error 2)
Found 40 game(s) for platform Origin
Found 1 game(s) for platform Gog
Saved 69 shortcuts
Finished synchronizing games in: 11.0708ms
Found 74 shortcuts for user: C:\Program Files (x86)\Steam\userdata\60957330
Error getting shortcuts from platform: Legendary
The system cannot find the file specified. (os error 2)
Found 40 game(s) for platform Origin
Found 1 game(s) for platform Gog
Saved 74 shortcuts
Finished synchronizing games in: 9.6156ms
Found 69 shortcuts for user: C:\Program Files (x86)\Steam\userdata\81110563
Error getting shortcuts from platform: Legendary
The system cannot find the file specified. (os error 2)
Found 40 game(s) for platform Origin
Found 1 game(s) for platform Gog
Saved 69 shortcuts
Finished synchronizing games in: 10.7668ms
Found 69 shortcuts for user: C:\Program Files (x86)\Steam\userdata\ac
Error getting shortcuts from platform: Legendary
The system cannot find the file specified. (os error 2)
Found 40 game(s) for platform Origin
Found 1 game(s) for platform Gog
Saved 69 shortcuts
Finished synchronizing games in: 11.8046ms
Checking for game images
Searching for AMAZONS
Searching for HITMAN 2 Standard
Searching for Metro Exodus Enhanced Edition
Searching for A Total War Saga: TROY
Searching for Ticket to Ride
Searching for Sam's Story Enhanced Edition
Searching for HITMAN 2 Expansion
Searching for Sid Meier's Civilization VI
Searching for HITMAN 1 GOTY Upgrade
Searching for Carcassonne
Searching for AMAZONS
Searching for HITMAN 2 Standard
Searching for Metro Exodus Enhanced Edition
Searching for A Total War Saga: TROY
Searching for Ticket to Ride
Searching for Sam's Story Enhanced Edition
Searching for HITMAN 2 Expansion
Searching for Sid Meier's Civilization VI
Searching for HITMAN 1 GOTY Upgrade
Searching for Carcassonne
Searching for Total War: Attila
Searching for Apex (Origin)
Searching for GTA V Rage
Searching for Escape from Tarkov
Searching for HITMAN 3
Searching for AMAZONS
Searching for HITMAN 2 Standard
Searching for Metro Exodus Enhanced Edition
Searching for A Total War Saga: TROY
Searching for Ticket to Ride
Searching for AMAZONS
Searching for HITMAN 2 Standard
Searching for Metro Exodus Enhanced Edition
Searching for A Total War Saga: TROY
Searching for Ticket to Ride
Searching for Sam's Story Enhanced Edition
Searching for HITMAN 2 Expansion
Searching for Sid Meier's Civilization VI
Searching for HITMAN 1 GOTY Upgrade
Searching for Carcassonne
Searching for AMAZONS
Searching for HITMAN 2 Standard
Searching for Metro Exodus Enhanced Edition
Searching for A Total War Saga: TROY
Searching for Ticket to Ride
Searching for Sam's Story Enhanced Edition
Searching for HITMAN 2 Expansion
Searching for Sid Meier's Civilization VI
Searching for HITMAN 1 GOTY Upgrade
Searching for Carcassonne

**Comment by PhilipK** [comment]
Hi, that is wierd.. Have you tried the cli version?
Also what version are you using? Have you tried the newest version?

I can see that you have legendary synch enabled but it is not installed (or atleast not able to find it). Can you try to disable it.

**Comment by deltoran0** [comment]
> Hi, that is wierd.. Have you tried the cli version? Also what version are you using? Have you tried the newest version?
> 
> I can see that you have legendary synch enabled but it is not installed (or atleast not able to find it). Can you try to disable it.

I tried disabling legendary synch in the GUI version, but that didn't resolve the issue.
However the CLI version worked perfectly with the same config file

Both were the latest version.

Thanks for the help & keep up the good work!
