### ISSUE TITLE
BoilR destroys Shortcuts addad by "Steam ROM Manager"

### ISSUE THREAD

**Issue by NightHammer1000** [PhilipK/BoilR#122]
I recently noticed that BoilR removes all my Roms added by Steam ROM Manager from Steam.

This wasn't the case a few Versions back. Something must have changed here. I started noticing it with the Release of the Flatpak Version.

To Reproduce:

- Stop Steam
- Setup Steam ROM Manager and Import a few Games.
- Start Steam
- See the Roms in Steam
- Stop Steam
- Run BoilR
- Start Steam
- See the BoilR Shortcuts but the ROM Manager Games are gone.

**Comment by PhilipK** [comment]
Thanks for this bug report, I will try to reproduce it and set up an automatic test so it doesn\t happen again

**Comment by NightHammer1000** [comment]
No Problem. I know VDFs can be a pain to work with.

**Comment by PhilipK** [comment]
@NightHammer1000  I am having a hard time recreating this. 
Could you try to set up some roms throug  rom manager and then upload your shortcuts.vdf file? Then I am sure that I can solve your specific issue.

**Comment by NightHammer1000** [comment]
Will do when I am back at Home later today.

**Comment by NightHammer1000** [comment]
Somehow it fixed itself again with the newest Version.
Works as intendet again.
