### ISSUE TITLE
BoilR needs to set STEAM_COMPAT_DATA_PATH for Origin shortcuts on Linux

### ISSUE THREAD

**Issue by bkoehle2** [PhilipK/BoilR#127]
I installed Titanfall 2 from Origin, and BoilR detects it properly and will import it. But the method from which I installed it requires me to change the launch options to get it to launch correctly (the default BoilR launch options appear to launch the installer again via Origin).

Once I changed those, I unchecked Titanfall 2 from BoilR, in hopes it would just leave the existing shortcut, as I discovered it will overwrite those launch options when left checked. But when I uncheck it, it also removes the shortcut from Steam. 

This is similar to #122 but with the additional note of BoilR overwriting a modified shortcut I figured I'd make my own issue to separate things. 

I have the VDF files from Steam, but Github doesn't seem to like attaching them, what's the best way to share those with you for troubleshooting?

**Comment by PhilipK** [comment]
Are you on Windows?

**Comment by bkoehle2** [comment]
I apologize for not clarifying. My desktop is Windows but the system in question with BoilR is a Steam Deck.

**Comment by PhilipK** [comment]
This is kind of a feature.
BoilR keeps track of which shortcuts it has added before so it can remove them again if people unselect it. If I stopped BoilR from removing its own shortcuts it it would just keep adding new shortcuts over and over.
Can you give an example of how the launcher options are wrong for origin?
I assume you have installed origin through proton on steam deck?

**Comment by bkoehle2** [comment]
Correct, Origin is installed through Proton. I followed this guide from Reddit, https://www.reddit.com/r/SteamDeck/comments/tx6srv/guide_installing_origin_on_the_steam_deck_the/.

The launch options provided by BoilR do launch Origin, but it prompts to install Titanfall 2 in my use case. And even when canceling the installer prompt Origin doesn't seem to detect or allow me to locate the already installed files. 

When I update the launch options as suggested in the Reddit post, Origin still launches, but it detects and allows me to run TF2 from that instance.

**Comment by PhilipK** [comment]
Can you give me a concrete example of what is needed in the launch options?
What do you change it form, and what do you change it too?
Then I can make BoilR do that instead of what it does now.

**Comment by bkoehle2** [comment]
Of course. 

The BoilR default launch options are (including quotes): "origin2://game/launch?offerIds=Origin.OFR.50.0001452&autoDownload=1&authCode=&cmdParams="

The launch options required to launch properly are: STEAM_COMPAT_DATA_PATH="/home/deck/.local/share/Steam/steamapps/compatdata/{ORIGIN NUMBER}" %command%

The {ORIGIN NUMBER} comes from the Wine prefix on my system, which in my case is 3633206593. I can't say for certain that those launch options would be universally compatible with all install methods though. 

While pulling that information, I'm also coming to the realization that BoilR is making the launch target the Origin executable rather than the TF2 exe deeper within.

**Comment by bkoehle2** [comment]
It looks like a garbled mess because Notepad++ doesn't like the file format, but I pasted what I could from opening the VDF file.

AppName Titanfall2 Exe "/home/deck/.steam/steam/steamapps/compatdata/3633206593/pfx/drive_c/Program Files (x86)/Origin/Origin.exe" StartDir  icon /home/deck/.steam/steam/userdata/247305271/config/grid/3752396355-icon.ico ShortcutPath  LaunchOptions "origin2://game/launch?offerIds=Origin.OFR.50.0001452&autoDownload=1&authCode=&cmdParams="

**Comment by PhilipK** [comment]
Yeah, the VDF format is binary and a mess to work with :-) 
But it makes sense, BoilR needs to set the STEAM_COMPAT_DATA_PATH to that of the wine installation so proton does not create a new compat folder which will then make origin not able to find the installed game.
I will update the issue name to reflect this.

**Comment by PhilipK** [comment]
This will be a problem for Epic installed through Proton as well.

**Comment by PhilipK** [comment]
I guess this is an example of https://github.com/PhilipK/BoilR/issues/51 and if one is solved so is the other :-)

**Comment by PhilipK** [comment]
This should be solved in the next release (most likely tonight 5 or so hours).

**Comment by PhilipK** [comment]
This should be solved in https://github.com/PhilipK/BoilR/releases/tag/v.1.3.5 if it is not for you, please let me know.

**Comment by bkoehle2** [comment]
I was able to successfully launch into TF2 with a BoilR made shortcut. I appreciate the assistance on this.

I know in this instance there was a problem with how BoilR was creating the shortcut, but you had said previously that BoilR will remember what games it makes shortcuts for. Do you think there is a use case for clearing some of that information? 

I suppose ideally BoilR makes the shortcuts correctly, but there may be instances where small adjustments to the launch options are necessary to get games to run. And if BoilR wipes that information every time an import is done, maybe there is a case for allowing the use to have BoilR "forget" it added a game so that adjustments can be made to the shortcut without it being overwritten (but still allowing BoilR to import the game art at first)?

**Comment by PhilipK** [comment]
I guess it would be possible to make a "forget this shortcut" feature in
the settings.
If you think it is worth it can you create a new issue for this?
Just copy paste what you already wrote, just so I don't forget 😊
