### ISSUE TITLE
Some games must be launched with epic uri

### ISSUE THREAD

**Issue by PhilipK** [PhilipK/BoilR#13]
Some games frail to launch when starting them from steam.
They simply state that you must "please launch form the epic launchers" and then crash.

The assumed solution is to launch the game using an epic uri:
com.epicgames.launcher://apps/b671fbc7be424e888c9346a9a6d3d9db%3A38c07a09dc174b69b756aa51890c3dd4%3ASalt?action=launch&silent=true

The uri can be put together from the manifest files that are in:
C:\ProgramData\Epic\EpicGamesLauncher\Data\Manifests

The current problem is that it is unknown how to distinguish these games from the others.
"Kingdom Hearts" and "Final Fantasy VII Remake Integrade" have been reproted to be problematic here: 
https://www.reddit.com/r/SteamDeck/comments/rocj1c/gog/hq4bpb2/?context=8&depth=9

**Comment by mogol1** [comment]
Here is the zip of my Manifests folder, hope this is helpful
[Manifests.zip](https://github.com/PhilipK/BoilR/files/7836468/Manifests.zip)
:

**Comment by paulysullivan** [comment]
Also seeing this error attempting to play Tony Hawk Pro Skater 1+2 from Heroic on the Steam Deck.

Launching it from Steam results in "Please make sure that the Epic launcher is installed before starting the game".

Happy to help debug if that is helpful.

**Comment by PhilipK** [comment]
In version v.1.0.7 it is now possible to select games to that needs to be opened through epic to work, check it out. If it doesn't work, i will reopen this issue.

**Comment by marmite22** [comment]
@PhilipK how do I go about selecting games that need to open through epic? I'm trying to launch Borderlands 2 and it's giving me an error about Epic needing to run.

I thought maybe there was something in the config file, but I can't seem to find the config.toml any more - did it move?

**Comment by PhilipK** [comment]
@marmite22 If you are on windows you choose that a game should launch through the epic launcher in the BoilR settings.
 I have not found a way to do it on deck yet.
Steam Deck calculator estimates 2 more weeks, so here is to hoping :-)
