### ISSUE TITLE
Unable to enter an API Key for SteamGridDB in Flatpak

### ISSUE THREAD

**Issue by dannymate** [PhilipK/BoilR#133]
Fedora Silverblue 36 using BoilR flatpak.
Whenever I try to type in the api key field it resets. I also can't paste from keyboard.

**Comment by PhilipK** [comment]
This needs fixed, but just so I understand the problem, does the little paste button work?

**Comment by dannymate** [comment]
![BoilR Issue 133](https://user-images.githubusercontent.com/26135914/168820861-c3d3a524-058f-4dc8-a7cd-58d9beb97df3.gif)

Here's a gif of the issue.

**Comment by PhilipK** [comment]
This is very weird, could you try the non flathub version? See if it is the same?

**Comment by dannymate** [comment]
I can't use the non-flathub version due to not having libssl1.1. I think fedora 36 like ubuntu 22.04 comes by default with openssl3/libssl3 so they have issues with version 1.1. Version 1.1 isn't in the package manager anymore. I could maybe install the an rpm but I don't really want to mess with my system too much. Sorry.

By the by Silverblue is an immutable OS like SteamOS3 if you weren't aware.

**Comment by dannymate** [comment]
So I got my brother who is running Fedora 35 Silverblue to try BoilR. He says that the paste from clipboard works but the typing doesn't initially. The typing only works after pasting from clipboard. He says he gets the same behaviour from the non flathub version. Not sure if that's the default behaviour but that's what happens.

**Comment by PhilipK** [comment]
@dannymate is it only the authentication input that acts like this?
Worst case you can edit the config.toml file and add the authentication key there btw.

**Comment by dannymate** [comment]
Just that one field having issues. Tested all the others and they're fine.

**Comment by PhilipK** [comment]
I have tried to streamline how the auth-key input is coded.
I don't know for sure if it will fix your problem, since I am not able to reproduce it, but if you say that the rest of the fields work then I don't see how it could not fix it .

I will let you know when the new release is out.

**Comment by PhilipK** [comment]
In version https://github.com/PhilipK/BoilR/releases/tag/v.1.3.9 I have streamlined the input field. I assume that it fixes the issue. If it does not, let me know and I will reopen this issue.
(Flatpak normally takes 3-4 hours to be deployed, so remember to check the version number before you test it)

**Comment by dannymate** [comment]
I can type in the field now so thanks very much for that. But the Paste From Clipboard button still doesn't work.
