### ISSUE TITLE
Steam Flatpak Path with BoilR Flatpak

### ISSUE THREAD

**Issue by dannymate** [PhilipK/BoilR#134]
Fedora Silverblue 36 with BoilR Flatpak
The path for the steam flatpak directory is:
/var/home/<username>/.var/app/com.valvesoftware.Steam/.steam/steam/

It's quite a pain to type in so a paste function would be useful. It also doesn't get found automatically if that's possible to add, even better..

**Comment by PhilipK** [comment]
I think the solution here is to look for the  /var/home//.var/app/com.valvesoftware.Steam/.steam/steam/ folder automatically, it should be easy enough to add. I will get it done asap.

**Comment by dannymate** [comment]
Thank you!!
