### ISSUE TITLE
Heroic GoG games are missing

### ISSUE THREAD

**Issue by wafflesoup** [PhilipK/BoilR#137]
standalone v1.3.6 on a Steam Deck with the flatpack version of Heroic. The Epic games that are installed show up but the GoG games don't.

**Comment by wafflesoup** [comment]
Just tried with the flatpak version of BoilR and that also had the same issue

**Comment by PhilipK** [comment]
There is a fix for finding GOG Games in version https://github.com/PhilipK/BoilR/releases/tag/v.1.3.9 (flatpak version normally takes a while to update).
I assume this fixes this issue so I am closing this issue. If it does not fix it, let me know and I will re-open it.
