### ISSUE TITLE
Heroic Launer Games not starting (steamdeck)

### ISSUE THREAD

**Issue by lublak** [PhilipK/BoilR#138]
Currently i use BoilR to import my games to steam für the steamdeck. I use Heroic Launer to install my epic games. It works fine if i launch them through the Heroic Launcher. I can play them.
But if i use the steam links (created by BoilR) it doesnt work.
Both applications are installed as flatpak.
I don't know if this helps: https://github.com/redromnon/HeroicBashLauncher

**Comment by cherokee93** [comment]
+1
I think because BoilR creates a shortcut to directly launch the .exe file on steam. Some games need Heroic to be open and launch them because I think they need the launcher open. 
For example, if I launch Horizon Chase Turbo through steam boilr shortcut it will get stuck on loading and never reaches menu, but if I launch it via Heroic it works just fine.

**Comment by PhilipK** [comment]
This is correct, BoilR currently creates a direct shortcut to the exe.
Some games need to be launched through heroic, and some will only work through the epic launcher.
Are you saying it always works through the HeroicBashLauncher? If so , i can recreate what they do to set up heroic shortcuts.

**Comment by cherokee93** [comment]
> If so , i can recreate what they do to set up heroic shortcuts.

I need to checkout if It works since i've stopped using heroicbashlauncher. But this 99% is the way to fix it aka make heroic launch the game

**Comment by lublak** [comment]
I haven't tried it myself yet, I'm not a linux pro yet, so I'm still a bit clumsy.
I can see if I can manage to try it out directly with HeroicBashLauncher.
I have only seen the project and thought that might help.
Currently I have only tested BoilR and 20 Epic Games. But none of them could be started via steam.
Except for deponia, they could all be opened directly via the launcher. (deponia has other problems: SteamAPI_Init() failed)

**Comment by PhilipK** [comment]
I am also working on launching games that have been installed through the epic store (installed via proton) that should also help.
Again, this will be so much easier to debug when I get a steam deck :-) 

But I will have a look at what parameters heroic needs to launch a game directly, and then make it an option to link directly to the exe or launch the game through heroic.

**Comment by PhilipK** [comment]
I tried HeroicBashlauncher and I can't really get it working, can someone confirm that it works for them before I invest any time into it?

**Comment by lublak** [comment]
@PhilipK i will give it a try:
https://github.com/redromnon/HeroicBashLauncher/wiki/Steam-Deck-(Flatpak)-Guide
But I can only do that later because I have to work first.

**Comment by Hatomike** [comment]
I can confirm that Heroic Bash launcher work for me.
I have been using it for a long time on my deck with shortcuts in gaming mode
The generated launch script doesn't need to have heroic launched in the background, it give Legendary every informations neccesary to launch the game. (You may need to launch the game at least once with heroic)

They also have a fix for games with special cahracters in them like Rocket League.

Be sure to use the correct version of Heroic Bash launcher, there is one compatible with Heroic appimage and another one for Heroic flatpak (There is also one for the deck based on the flatpak version)

**Comment by PhilipK** [comment]
So it looks like heroic bash launcher reads the heroic config file (which boilr does as well) and then stiches together a long launch command for legendary or gog:
https://github.com/redromnon/HeroicBashLauncher/blob/main/func/checkparameters.py

It should be doable, it will just take some time, hopefully I will have time for it this weekend.

**Comment by redromnon** [comment]
Hi there! I'm the dev of Bash Launcher. Just came across this issue. If you need any sort of help, feel free to ask.

**Comment by PhilipK** [comment]
Awesome, thanks. I think I have parsed it now, very nicely organized so it
was easy.
If you need help in the future with adding another launcher that BoilR can
do feel to ask as well.
The more options there are the better for the gaming community (and Linux
gaming in particular)

**Comment by redromnon** [comment]
Sure! Thanks to you too.

> The more options there are the better for the gaming community (and Linux
> gaming in particular)

You're absolutely correct. It's a win-win situation for everybody.

**Comment by PhilipK** [comment]
In version https://github.com/PhilipK/BoilR/releases/tag/v.1.3.9 I have added an option to launch games through the heroic launcher (look in settings). It should fix this issue.
If it does not, let me know, and I will re-open this issue.

**Comment by lublak** [comment]
@PhilipK works fine! :) thaaaanks <3
One more thing I noticed. It would be handy to have the "start with launcher checkbox" directly in the main screen.
![grafik](https://user-images.githubusercontent.com/44057030/169770487-1a22fd2a-9a65-4163-be68-c14a597a2757.png)

**Comment by PhilipK** [comment]
@lublak What about a checkbox in settings that flips the default? So all games are by default launched through heroic but you can go into settings if a certain games should be launched directly?

**Comment by lublak** [comment]
@PhilipK I'm fine with that too.
Since most of the games (at least my gamesI) have to be started with heroric launcher.
I was only surprised that nothing changed when I updated and re-imported.
It was only a few minutes later that I found the option.

Of course, a no-ui and auto-close option in Heroic Launcher would also be interesting. But that's another place where I can ask.

**Comment by lublak** [comment]
https://github.com/PhilipK/BoilR/pull/154
