### ISSUE TITLE
I had to remove Boilr definitely from my Steam Deck because it broke my system twice and consequently I had to reinstall everything again, I lost almost two days configuring things again

### ISSUE THREAD

**Issue by Sightlyjester** [PhilipK/BoilR#140]
You see, the error is that, not always, but sometimes when I run boilr to update covers of my games, instead of putting that it looks for images it does nothing and stays on the word "done". Finally, when I go back to game mode after this, all apps, Launchers from other stores, and emulator covers are gone, breaking 90% of my Steam Deck library. I attest that your app is very useful, but I have had to abandon it due to these very serious bugs that mess up my Steam Deck and waste a lot of my time. I hope you detect the problem and fix it.

**Comment by PhilipK** [comment]
Really sorry to hear that BoilR messed up your configuration!
I can't give you back the time that you last configuring your deck, but I will try to prevent it from happening in the future.
I will create a feature that lets you back up and restore your configuration, every time before BoilR runs it will create a backup of your shortcuts file. Then you should be able restore if anything like this happens again, or if another tool messes them up:

https://github.com/PhilipK/BoilR/issues/141

**Comment by PhilipK** [comment]
@Sightlyjester A couple of questions about your setup:
Are you running BoilR as a flatpak?
What other tools have you used to import shortcuts with?
Do you still have the broken shortcuts file? If so could you upload it as a zip? I would like to investigate what went wrong.

**Comment by PhilipK** [comment]
Also I will also make this:
https://github.com/PhilipK/BoilR/issues/142

It should let you use BoilR to ONLY handle images, and nothing else.

**Comment by PhilipK** [comment]
I can confirm this is a problem with the combination of Boilr and Steam ROM manager

**Comment by PhilipK** [comment]
This is solved in version 1.3.8 (the newest release).
It should be available on flathub shortly.

I am going to close this issue, but if something is still wrong for you, let me know and I will reopen this.

**Comment by Sightlyjester** [comment]
> 
Sorry, I was a little busy today and I could not answer the questions you asked me about my mistake. Yes indeed the error occurred when I ran Steam ROM manager together with Boilr at a nearby time, I see that you have seen this variable because I posted it on Reddit when I reported the problem and I see that you have answered me there as well. A thousand thanks for fixing your problem and I'm glad if I was able to contribute something in its possible solution. I find your program very useful for my library in my Steam Deck and I'm glad to be able to use it again without fear of losing everything again. If I experience a similar error again I will let you know :)

**Comment by PhilipK** [comment]
@Sightlyjester I am glad that it works for you now!

I have also opened a pull request on Steam ROM manager to ensure that it gets fixed for more than just BoilR:
https://github.com/SteamGridDB/steam-rom-manager/pull/312

Other will run into the same problem in the future, so if you have time, give it a like to let them know that it is important to fix.
