### ISSUE TITLE
[Request] Bottles Integration?

### ISSUE THREAD

**Issue by bayazidbh** [PhilipK/BoilR#143]
Hi, I just found this project today (was looking for Steam while testing Endless OS). The project seems interesting, and Lutris integration would mean that it has an option for Wine game. That said, setting up on Lutris is rather tedious in my opinion, so I've been looking into the option of using [Bottles](https://github.com/bottlesdevs/Bottles) instead.

Would it it be possible to have a Bottles integration as well? Bottles does have a Library/Gallery mode and CLI option now, so I'd imagine it might be possible to read and parse those? Thanks regardless.

**Comment by PhilipK** [comment]
Sounds interesting.
Do you have any pointers to its CLI  and how to use it? 
I can't seem to find anything.

**Comment by bayazidbh** [comment]
They first talked about it in the [2022.3.28 release blog post](https://usebottles.com/blog/release-2022.3.28/) and then later on announced .desktop support for [2022.4.28](https://usebottles.com/blog/release-2022.4.28/), it's also on [the site's documentation page under advanced section](https://docs.usebottles.com/advanced/cli).

**Comment by XargonWan** [comment]
This may be helpful: https://www.reddit.com/r/SteamDeck/comments/unhnbp/method_for_adding_a_bottles_shortcuts_to_game/

**Comment by redoxeon** [comment]
> Sounds interesting. Do you have any pointers to its CLI and how to use it? I can't seem to find anything.

Found these, if it helps!
- https://docs.usebottles.com/advanced/cli
- https://docs.usebottles.com/advanced/use-bottles-as-wine-command
- https://docs.usebottles.com/advanced/xdg-open

**Comment by PhilipK** [comment]
The next version of BoilR will have a Bottles integration.

**Comment by PhilipK** [comment]
The newest version has Bottles integration:

https://github.com/PhilipK/BoilR/releases/tag/v.1.5.0

(give it a couple minutes after this post for it to build the new versions, and for flatpak a couple hours)
