### ISSUE TITLE
Find Epic Store games when installed through Proton (Linux)

### ISSUE THREAD

**Issue by PhilipK** [PhilipK/BoilR#157]
If you follow one of the popular guides to install Epic Luancher through proton, BoilR does not pick up the games.
The problem is that it does not find the manifest files, and even if they are manually pointed to the manifest files themselves refer to a path that is relative to C: which should be relative to the compatdata folder.

Another problem is that the Epic launcher does not seem to launch a game when given a launch url in the same way it does on windows. Even if a shortcut is created that sets the compat folder and gives to url to the exe, the Epic launcher will just start but it will not launch the game.

Here is an example of a shortcut that only opens the launcher and does not load the game:

Target:
"/home/philip/.steam/steam/steamapps/compatdata/3532403833/pfx/drive_c/Program Files (x86)/Epic Games/Launcher/Engine/Binaries/Win32/EpicGamesLauncher.exe"
Start in:
"/home/philip/.steam/steam/steamapps/compatdata/3532403833/pfx/drive_c/Program Files (x86)/Epic Games/Launcher/Engine/Binaries/Win32/EpicGamesLauncher.exe"
Launch options:
STEAM_COMPAT_DATA_PATH="/home/philip/.steam/steam/steamapps/compatdata/3532403833" %command% "com.epicgames.launcher://apps/tulip%3A6a398fcd7a464ea1a69fea1f0b0281cc%3Afe6c485736bc4ed48c835290ce48099b?action=launch&silent=true"

If anyone knows how to get Epic to actually launch the game through a commands, BoilR can create it, but I cannot figure out how it should be done.

**Comment by PhilipK** [comment]
I am assuming this works for steam deck now, so will close this until someone says otherwise :-)

**Comment by ictnetw** [comment]
It is not working yet. Still same issue. Launcher starts but the game not.
