### ISSUE TITLE
Ui crashes and cmd doesnt do anything when trying to download images from steamdb

### ISSUE THREAD

**Issue by Poplix09** [PhilipK/BoilR#16]

**Comment by PhilipK** [comment]
If you run the program (cli or Ui) from the cmd /terminal what is the output?

**Comment by PhilipK** [comment]
In the newest release there are new fixes for  issues that sound a lot like this. Can you see if this is still a problem in the newest release?

**Comment by PhilipK** [comment]
I am going to close this issue, I assume that the problem has been fixed in the newest version. If they have not, please just reopen the issues again.
