### ISSUE TITLE
Steam Deck: Heroic Games Launch in Background

### ISSUE THREAD

**Issue by krelltunez** [PhilipK/BoilR#162]
Hi, after pulling my hair out trying to use Heroic Bash Launcher, I finally gave up and tried Boilr.  It looks promising and I'm looking forward to using it for other launchers.  Right now, I'm focused on Heroic.

Setup of the shortcuts seems to work just fine.  Games show up in Steam with artwork and all looks good.  Problem is, when I start a game (I've tried Kena and Outer Wilds), the game loading screen shows (Steam UI) and the game loads in the background.  In both cases, I can hear the game audio, but I cannot figure out how to bring the game to the front (since, as far as I know, Game Mode does not have ALT-TAB).

I cannot figure out why this isn't working!  Happy to test things if helpful.  FYI, I'm on SteamOS Beta, Steam UI Stable, latest version of Heroic Games Launcher and Boilr (both via Flatpak).

THANK YOU!

EDIT:  It occurred to me that this is probably a Heroic Games Launcher issue, not a Boilr issue.  As far as I can tell, the shortcut is set up properly and should work (as evidenced by this working just find in Desktop Mode on the Steam Deck).

**Comment by PhilipK** [comment]
If you launch the game from heroic directly, does it then work?

Have you tried to go into boilr settings and change between "launch directly" and "launch through heroic"? (if you are launching directly, make sure that you have a proton version set on the steam shortcut, if it is through heroic then make sure proton is off)

**Comment by PhilipK** [comment]
I am going to close this issue here on BoilR, but if you find that BoilR needs to do something different to enable Heroic to launch the games better let me know and I will reopen this.

**Comment by krelltunez** [comment]
Sounds good. FYI, launching directly from Heroic has always worked for me. Oh and the Boilr shortcuts also work in desktop mode. So this doesn't appear to be a Boilr issue at all.

**Comment by krelltunez** [comment]
Just to provide a further update, I went with the nuclear option - uninstalled all games, game shortcuts, heroic launcher AND Boilr (including user data in home/deck/.var).  Reinstalled heroic, got 1 game working through that, then installed Boilr.  First tried the shortcut from desktop mode, and after confirmed it worked, went into Game Mode and tried it and... voila!  It worked!

No idea what was happening the first time.

**Comment by PhilipK** [comment]
Thanks for the update! Glad it worked out.

**Comment by oscarsiles** [comment]
I am having issues with GOG games installed through heroic as these shortcuts don't seem to run through heroic but to the exes directly. In Boilr settings only Epic games are showing under Heroic as well, so I would guess these are related.

**Comment by PhilipK** [comment]
@oscarsiles can you open a new issue for this? I think it is something else, just so I can track it.

**Comment by PhilipK** [comment]
@oscarsiles I found the bug, gog games where not shown in the list of "launch through heroic". The newest version 1.3.18 has the fix.
