### ISSUE TITLE
Import Epic Games from original launcher on the Steam Deck

### ISSUE THREAD

**Issue by williambroad** [PhilipK/BoilR#165]
Hi there.

I am having huge trouble getting BoilR to recognize any of my Epic Games.
I installed the Epic Games Launcher using Proton and then imported it as a non Steam game.
I installed Assassins Creed Origins and it runs perfectly using the Epic launcher.
However, I would like to run it as the game per se under SteamOS using a BoilR shortcut.

After a lot of failures I even tried the following command lines in the config of BoilR...

[epic_games]
enabled = true
location = "/home/deck/.local/share/Steam/steamapps/compatdata/3091106007/pfx/drive_c/ProgramData/Epic/EpicGamesLauncher/Data/Manifests"
create_symlinks = true

And no matter how I change any of the location info I get nothing.
Any help would be greatly appreciated.
Thanks!

**Comment by williambroad** [comment]
BoilR doesn‘t recognize the games in the first place…

In the meantime, I found a nice workaround using Lutris and Steam shortcuts. Works like a charm.

Thanks for getting back here though.

**Comment by PhilipK** [comment]
I would recommend lutris as well. BoilR can find those shortcuts, plus it
can find the game art even if you use lutris to create the shortcuts.
