### ISSUE TITLE
Hitman 3 from Heroic always uses native Heroic even if its not Installed.

### ISSUE THREAD

**Issue by NightHammer1000** [PhilipK/BoilR#172]
Only have the Flatpak Version on the Deck.
Strangely all the other Heroic Games create their Shortcuts correctly.
Only Hitman 3 uses the native Heroic Command.

Lets me Wonder if its Hard-coded somewhere :P

**Comment by PhilipK** [comment]
Have you had the native version installed at some point in the past?

**Comment by NightHammer1000** [comment]
Nope. I actually reinstalled the Deck yesterday because I tried out Windows on it.

**Comment by PhilipK** [comment]
Is this still a problem in the newest version of boilr?

**Comment by NightHammer1000** [comment]
Nope. Works as intented now.
