### ISSUE TITLE
Boilr does not import or recognize Epic Games Store games in Steam Deck

### ISSUE THREAD

**Issue by Sightlyjester** [PhilipK/BoilR#177]
Hi, it's a shame because although heroic games import them well and add them to the game mode in addition to their covers...it seems that boilr although it says it imports the ones from Epic Games Store really doesn't do it well. I don't know why it doesn't recognize them or find them, but I would like it to be fixed in an update because I don't like adding them manually to the game mode.

**Comment by PhilipK** [comment]
Are you just not seeing the games at all? Or are they imported and then they don't work?

**Comment by PhilipK** [comment]
To verify this, can you try to use the native version. does it pick up the epic games?

**Comment by sickhate** [comment]
Yeah im using the boilr from flatpak and it doesnt pick up any games from epic launcher

**Comment by PhilipK** [comment]
How did you install your epic launcher? I just tried installing it myself, by just running the installer from stream (as a 3rd party game) and BoilR picks up the games.

**Comment by sickhate** [comment]
installed it threw the desktop mode an usin proton to install by lanching the installer within steam...im installing the games on sd card tho that may b the issue?!

**Comment by sickhate** [comment]
im using has launch STEAM_COMPAT_MOUNTS=/run/media/mmcblk0p1/ DXVK_ASYNC=1 %command%

**Comment by PhilipK** [comment]
Where are you adding those parameters? To the epic launcher shortcut in steam?

**Comment by sickhate** [comment]
Yes i have added it in the shortcut i created for the EGS launcher...but its because i need to install on the sd because i got no space left on the deck...

**Comment by sickhate** [comment]
Hi chris any suggestions on how can i have boirl scanning sdcard?

**Comment by PhilipK** [comment]
I will have to try it out myself, but I think that you are right, most likely it is because of the sdcard.
I think the problem is that BoilR looks at manifest files, those manifest files store the paths of where the games are. Problem is, most likely they are "fake windows paths" and they are actually stored on the SD. When BoilR looks at the paths it does not know this.
I will have to look at what the strategy is for where the games actually are stored and what epic is told about the path.

**Comment by sickhate** [comment]
Sweet! I dont have enough space on the deck so i need to get them on sdcard...

**Comment by TrentonBlackburn** [comment]
Yeah, having the same issue here. My approach to steam deck storage has been: Steam games on internal drive, but everything else (Emulators, non-steam windows apps, alternate launchers) all go on the MicroSD.

So I downloaded Origin/Epic Games through lutris since they have the easy installation process. Then, when I downloaded the games, I targeted a new folder I made on my MicroSD instead of the emulated C:/ locations it defaulted to. 

BoilR is unable to find Origin or Epic games if done this way.

**Comment by PhilipK** [comment]
This version should have a fix that should help with this.
Can someone try it?
https://github.com/PhilipK/BoilR/releases/tag/v.1.7.1

**Comment by sickhate** [comment]
Will try in a few minutes

**Comment by sickhate** [comment]
![Screenshot_20221012_213923](https://user-images.githubusercontent.com/83520112/195443337-dfe697d4-fdaa-4ef7-be65-b4202dff17a6.png)

**Comment by sickhate** [comment]
![Uploading Screenshot_20221012_214028.png…]()
![Uploading Screenshot_20221012_214040.png…]()

**Comment by sickhate** [comment]
![Screenshot_20221012_214028](https://user-images.githubusercontent.com/83520112/195444306-ce1699d6-eb34-4037-8382-d345ac26346e.png)
![Screenshot_20221012_214040](https://user-images.githubusercontent.com/83520112/195444327-13c06f6f-2eea-4203-b579-c782829dea3f.png)

**Comment by sickhate** [comment]
it seems i got 1.7.0....from flatpak

**Comment by PhilipK** [comment]
The pre release is not on flatpak, only the standalone executables. Just wanted to make sure that it works with a prerelease, since flathub is pretty much a one way street when updating.

**Comment by sickhate** [comment]
Ok ill update it via command and give it a try

**Comment by sickhate** [comment]
still nothing but picking up emulators
![Screenshot_20221013_102643](https://user-images.githubusercontent.com/83520112/195559341-e8b702d1-d108-4e8b-96c2-b2a5ba37552d.png)

**Comment by PhilipK** [comment]
If you hover on the "failed finding games" games text, what is the error message ?

**Comment by sickhate** [comment]
Yes: manifests not found

**Comment by sickhate** [comment]
Maybe if it had an option to select where the games are installed? I dont think his  looking into sd card? Or maybe not readind the settings file?

**Comment by rlach** [comment]
Something seems really wrong here. 
I've tried following the tips for linux: https://github.com/PhilipK/BoilR/blob/main/tips_for_linux.md

It says "Set the path to EGS in the config.toml (or through the ui)" but there are two problems with it:

1. The config.toml doesn't seem to exist anywhere in the system(after launching the standlaone version and saving config, it reads the config when restarted). That, or filesearch on steam deck can't find it.
2. The UI has no section to set the path to EGS. All I can select is whenever I want to import, and if I want to launch the games trough the EGS.

This file https://github.com/PhilipK/BoilR/blob/main/configuration.md says `config.toml` should be created automatically, but it didn't. I've tried creating `config.toml` manually in the same folder as the boilr standalone, set the location there, but it doesn't seem to do anything. Even if I set epic import to false in the file it doesn't disable it in the ui.

I tried installing flatpak version, and look for the config file there, but also couldn't find it. There is also no location section for epic in flatpak version. I don't think boilr can find the EGS automatically inside the protons, so without setting the paths I can't see how it should work.

I've tried installing egs trough lutris as in the readme, but also I've tried doing it manually trough "add to steam", and neither method is found by boilr.

**Comment by PhilipK** [comment]
The standalone config file is located at:
`/home/deck/.config/boilr/config.toml`

You should see a:
```
[epic_games]
enabled = true
```

**Comment by PhilipK** [comment]
2. The reason there is no "path" anymore, is that BoilR now does a search through all the compat folders itself. On Windows it uses the windows registry.

So something is wrong if it said it failed. I will just have to do some more testing when I get some free time.

**Comment by thelaif** [comment]
Has there been a solution to this yet? I'm having the same issue.

**Comment by PhilipK** [comment]
This should be solved in the newest release
