### ISSUE TITLE
Panic if vsync is not available

### ISSUE THREAD

**Issue by theCalcaholic** [PhilipK/BoilR#180]
When I tried to run BoilR, it crashed for me with the following error:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NoAvailablePixelFormat', /run/build/boilr/cargo/vendor/eframe-0.18.0/src/native/run.rs:25:14
```

This is caused by egui/glutin attempting to use features that aren't supported by my GPU/driver (compare https://github.com/emilk/egui/issues/957). By playing around with the configuration in https://github.com/PhilipK/BoilR/blob/main/src/ui/uiapp.rs#L259-L263, I tracked it down to vsync.
This change in ui/uiapp.rs works around the issue for me:
```diff
    let native_options = eframe::NativeOptions {
        initial_window_size: Some(egui::Vec2 { x: 800., y: 500. }),
        icon_data: Some(get_logo_icon()),
+       vsync: false,
        ..Default::default()
    };
```

Might be an issue with the proprietary Nvidia driver on Wayland. Maybe it would be an option to make vsync configurable via command line parameter?

My system:

OS: Fedora 36
Desktop Environment: Gnome (Wayland)
GPU: Nvidia RTX 3080
Graphics driver: Nvidia (proprietary) 515.57

**Comment by PhilipK** [comment]
I have tested this on fedora silverblue with Wayland and  proprietary
nvidia drivers... Weird that it crashes for you.
I think that the solution is to make it possible to control from the
settings file. Unfortunately I am without a pc for a week minimum, so I
can't fix it till after. I will gladly accept a pull request for it if you
are up for it (I can do that from my phone, when I find a signal here and
there)

**Comment by theCalcaholic** [comment]
Well, I guess Nvidia + Wayland is a moving target currently, so things can break occasionally. I'll see, if I can provide a PR. In the meantime, don't stress yourself over it and enjoy your time off. :) As long as only I'm reporting this issue, it might not affect many people

**Comment by PhilipK** [comment]
I have merged a pull request that lets you start BoilR without V-Sync. I have not made it as a settings file thing, since it seems very very specific.
It will be in the next release (today)
