### ISSUE TITLE
Images click closes app

### ISSUE THREAD

**Issue by davfervar** [PhilipK/BoilR#181]
When I click the images option on my steamdeck closes the app instantaneously, any fix?

**Comment by PhilipK** [comment]
First, have you set up a steamgriddb.com api key?
Second, can you try to run the app through a terminal, and post the log messages here.

flatpak run io.github.philipk.boilr

**Comment by trigger7** [comment]
Same here, it was working before, but crashes since latest flatpak update.
Full logs with backtrace enabled :

```
(101)(deck@steamdeck ~)$ RUST_BACKTRACE=full flatpak run io.github.philipk.boilr
Setting for platform EGS are invalid, reason: Manifests not found
Setting for platform Legendary are invalid, reason: No such file or directory (os error 2)
Setting for platform Itch are invalid, reason: Path not found: Some("/home/deck/.itch/db/butler.db-wal")
Setting for platform Origin are invalid, reason: Default path not found
Setting for platform Gog are invalid, reason: Could not find path: "/home/deck/Games/gog-galaxy/drive_c/ProgramData/GOG.com/Galaxy"
Found 1 game(s) for platform Heroic
Setting for platform Flatpak are invalid, reason: No such file or directory (os error 2)
thread 'main' panicked at 'Should have steam user: SteamFolderNotFound { location_tried: "\"/home/deck/.steam/userdata\"" }', src/ui/ui_image_download.rs:331:59
stack backtrace:
Setting for platform EGS are invalid, reason: Manifests not found
   0:     0x55be82fa56bd - <unknown>
   1:     0x55be82fce3cc - <unknown>
   2:     0x55be82f9e401 - <unknown>
   3:     0x55be82fa7075 - <unknown>
   4:     0x55be82fa6ce9 - <unknown>
   5:     0x55be82fa7648 - <unknown>
   6:     0x55be82fa74f7 - <unknown>
   7:     0x55be82fa5b74 - <unknown>
   8:     0x55be82fa7229 - <unknown>
   9:     0x55be82920593 - <unknown>
  10:     0x55be82920683 - <unknown>
  11:     0x55be8298a670 - <unknown>
  12:     0x55be829295ef - <unknown>
  13:     0x55be82929837 - <unknown>
  14:     0x55be82934fac - <unknown>
  15:     0x55be8298d4f5 - <unknown>
  16:     0x55be82b34bb3 - <unknown>
  17:     0x55be82b4ac40 - <unknown>
  18:     0x55be82b3eecd - <unknown>
  19:     0x55be82b4773d - <unknown>
  20:     0x55be82b64e3a - <unknown>
  21:     0x55be82b6798f - <unknown>
  22:     0x55be82b4b1dc - <unknown>
  23:     0x55be8298da24 - <unknown>
  24:     0x55be82936d4d - <unknown>
  25:     0x55be829fd573 - <unknown>
  26:     0x55be829b3539 - <unknown>
  27:     0x55be82f9783e - <unknown>
  28:     0x55be82936e62 - <unknown>
Setting for platform Legendary are invalid, reason: No such file or directory (os error 2)
Setting for platform Itch are invalid, reason: Path not found: Some("/home/deck/.itch/db/butler.db-wal")
Setting for platform Origin are invalid, reason: Default path not found
  29:  Setting for platform  Gog  are invalid, reason:  Could not find path: "/home/deck/Games/gog-galaxy/drive_c/ProgramData/GOG.com/Galaxy"0x
7fd627daab80 - __libc_start_main
  30:     0x55be8292083e - <unknown>
  31:                0x0 - <unknown>
Found 1 game(s) for platform Heroic
Setting for platform Flatpak are invalid, reason: No such file or directory (os error 2)
```

**Comment by PhilipK** [comment]
Is this on the steam deck?

Looks like it can't find a steam installation, any idea where your steam
folder actually is?

**Comment by PhilipK** [comment]
I see now that it is on a deck... I wonder what changed. Unfortunately I am
currently in the middle of nowhere in Norway, without access to a pc. If
anyone can help debug this I would be grateful.

**Comment by PhilipK** [comment]
After you set the correct path, can you then try to run an import, even if
you select nothing to import it will save your settings when you run an
import.

Alternatively you can edit the settings file manually.

**Comment by davfervar** [comment]
It just work for me using the path /home/deck/.steam/steam/   and had no problems saving the settings

**Comment by davfervar** [comment]
I had to use the versión downloaded from the web page because directly, because from steam store doesnt work

**Comment by trigger7** [comment]
Running an import does indeed save the new path.

I would suggest adding a save button in the settings page, as per #182
It would also be nice if BoilR wouldn't crash if the path is incorrect, and display instead an error message explaining the issue.

**Comment by NightHammer1000** [comment]
I actually never had a crash before if the Path was not correct.
It just loads indefinite.

**Comment by PhilipK** [comment]
Alright, made it so it shows an error message when settings are invalid instead of just crashing.
This will be in the next release (today)

**Comment by MrThista** [comment]
im having the same issue still, also on steamdeck, error log below, steam location has been set to /home/deck/.steam/steam/: 
```
(deck@steamdeck ~)$ flatpak run io.github.philipk.boilr
Found 1 game(s) for platform Itch
Setting for platform Lutris are invalid, reason: No such file or directory (os error 2)
Setting for platform Flatpak are invalid, reason: No such file or directory (os error 2)
thread 'main' panicked at 'source slice length (296700) does not match destination slice length (395600)', /run/build/boilr/cargo/vendor/image-0.24.3/./src/codecs/webp/extended.rs:462:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by PhilipK** [comment]
That looks like some kind of really broken image it is trying to load.
Can you try to delete the thumbnails folder.
It should be in ~/.var/app/io.github.philipk.boilr/. thumbnails or
something like that (on phone, can't check right now).

If it is the case, I am thinking a fix is to delete a thumbnail if it fails
to load (instead of a crash).

**Comment by PhilipK** [comment]
Another way to test this theory is to run the native version, it does not
share its config folder with the flatpak version.

**Comment by MrThista** [comment]
Got the issue in both versions and seems to remain even when i delete the whole config folder and start adding again, oddly it did work on first install.
