### ISSUE TITLE
Save option?

### ISSUE THREAD

**Issue by Bboy486** [PhilipK/BoilR#182]
When running the script I am able to add the api and check off the options I want but there is no option to save. Also there is no option under backup to create a backup.

**Comment by NightHammer1000** [comment]
The Options get Saved once you run an Import.
But yeah. This should probaply be changed. Maybe save if you click off the Settings Page.

**Comment by Bboy486** [comment]
Another issue is when I run an import there is no visible progress bar and the import never shows completed.

**Comment by PhilipK** [comment]
Adding a save button to the settings menu in the next release (today)
