### ISSUE TITLE
Itch.io games seem to take endlessly to import

### ISSUE THREAD

**Issue by thekingoflorda** [PhilipK/BoilR#183]
I’m on a steamdeck trying to import a short hike. I’ve added the api key for steamgridsDB, but that didn’t work
Not sure what to do.

**Comment by PhilipK** [comment]
Have you tried any other platforms? Is this only for itch.io?

**Comment by PhilipK** [comment]
Could you try to run BoilR through a terminal and post the terminal output here?

**Comment by PhilipK** [comment]
I am not able to reproduce this, is this still a problem for you?

**Comment by PhilipK** [comment]
I am assuming that this is solved in the newest version, if it is not, please let me know and I can reopen this issue.
