### ISSUE TITLE
[Bug] An Anime Game Launcher shoes non genshin cards

### ISSUE THREAD

**Issue by Merith-TK** [PhilipK/BoilR#188]
So there is an program called "An Anime Game Launcher", it downloads, patches, and runs Genshin Impact on linux,

there is an problem with it and how steam game mode works, GameMode seemingly relies upon the initial window to detect the process tree, so If I name my shortcut anything other than "An Anime Game Launcher", Steam cannot focus on the game, and it will instead run in the background and steam will not acknowledge it is even running

but this also means I cant get titlecards from GridDB because BoilR searches, "An Anime Game Launcher" in griddb

**Comment by PhilipK** [comment]
I would suggest that you disconnect the BoilR shortcut (using the Disconnect feature), and then manually change the name of the shortcut in steam.
Then run BoilR again, and it will see the shortcut as a new shortcut and search for the new images.
You can also go in and change the steamgriddb id that BoilR will use for a shortcut, just check in the images tab.

**Comment by Merith-TK** [comment]
> then manually change the name of the shortcut in steam.

that 100% breaks steamdeck compatibility

steamdecks game mode focuses off windowed title, NOT process ID, which means if I name it "Genshin Impact" It will look for "Genshin Impact" and NOT "An Anime Game Launcher"

Same issue if I rename "PolyMC" or "MultiMC" to Minecraft, 
it expects "Minecraft", NOT what is presented, causing the program to open in the background with litterally no way to close it except for `ssh` and physically rebooting the deck, all while the deck will believe the game simply didnt launch in game mode

**Comment by PhilipK** [comment]
Okay, I think I misunderstood the issue then.

There is another workaround tho. If you open the "An Anime Game Launcher" shortcut in the images tab, and click the "these images are not for this game text" Then you can manually input another steamgrid id. So on stemagrid you can see that the id for Genshin Impact is: 5267777 from the url  https://www.steamgriddb.com/game/5267777

If you put that in the id input field and click the "clear all images" BoilR will now download images for Genshin Impact  instead.

Hope that helps.
