### ISSUE TITLE
Boilr won't find Itch.io games on the SD card

### ISSUE THREAD

**Issue by rickleone** [PhilipK/BoilR#197]
I'm using the 64GB version Steam Deck, and Boilr imported Itchio games to the Steam library pretty efficiently when the game directory was in the internal memory. Obviously I ran out of memory pretty soon, and I had to move the directory to the SD card, using the Itchio app, not manually.
I've set the new location of the game directory on Boilr (run/media/mmcblk0p1), left "create symlinks" flagged, but Boirl doesn't see the games anymore. The only logical thing that comes to my mind is that this app has a different way to parse file paths, since there isn't a browsing button yet.

**Comment by PhilipK** [comment]
What do you mean by (run/media/mmcblk0p1) in BoilR?

Do you still have some games on internal? If so does Boilr still see those?

**Comment by rickleone** [comment]
So, I've tried also to install the games on the internal memory, via ItchIo app, to specific the file path to the internal directory. But apparently, Boilr can't visualize ItchIo games no matter where they're located now, and I had erroneously attributed that to the new location.

**Comment by PhilipK** [comment]
@rickleone can you try to just clear the itch path setting and click save. That should let BoilR try to find the path itself again.

**Comment by rickleone** [comment]
Ok, I'm, a bit embarrassed, but I've deleted the boirl directory in the .var directory, just to get rid of old messed-up configuration files, and it was very very very effective, because now Boirl can see all the games, both internal memory and SD card.
So yeah, when in doubt, delete the configuration directory and start anew.
Also, there's a setting to make it automatically assign posters to the games?

**Comment by PhilipK** [comment]
If you go add an api key to steamgriddb in the setting , then it should
happen automatically.

**Comment by rickleone** [comment]
If you don't consider something that could be repaired by deleting the configuration folder as a bug, no, there's no bug.
