### ISSUE TITLE
Click to change image not working

### ISSUE THREAD

**Issue by nwg5817** [PhilipK/BoilR#205]
**Describe the bug**
Images tab changing hero/grid images doesn't do anything. 

**To Reproduce**
Go to Images tab, click Marvel's Spider-man Remastered
Change Hero and grid images. 
Back out, images stay the same, restart, images stay the same.

**Expected behavior**
Image changes when selecting a new image

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Steamdeck
 - BoilR Version 1.4.4

**Comment by nwg5817** [comment]
Something to do with the title of the game? Xemu works fine.

**Comment by nwg5817** [comment]
The images at the top generally don't work, and the ones all the way at the bottom do.

**Comment by PhilipK** [comment]
And this is only for official steam games, or also a problem for 3rd party shortcuts?

**Comment by nwg5817** [comment]
These are all third party lutris shortcuts.

**Comment by nwg5817** [comment]
You can anydesk into my deck if you want. Images folder crashing again, added a few new games. Spider-man reverted the images back after manual selection. Picking up NES game covers or something lol.

**Comment by PhilipK** [comment]
This shold be solved inversion:
https://github.com/PhilipK/BoilR/releases/tag/v.1.4.7

Once someone else confirms it works for them, this issue can be closed.

**Comment by nwg5817** [comment]
Seems like its doing well now. Picked up all my non-steam games, right pictures and was able to change the ones that werent. Nice job.

**Comment by PhilipK** [comment]
What if you try another image?could it be image specific?
