### ISSUE TITLE
No way to correct wrong game image if none of the auto-suggested alternatives are correct

### ISSUE THREAD

**Issue by Swizzler121** [PhilipK/BoilR#213]
**Describe the bug**
There doesn't appear to be a way to correct BoilR if it cannot find the steam grid entry for a game, even in the alternate suggestions

**To Reproduce**
1. Download ET Legacy launcher from flatpak store (Wolfenstein: Enemy Territory Launcher)
2. Open BoilR and select ET Legacy from the list
3. Let the program try and find images
4. It will pull the wrong images, so click on the title under images to correct
5. Click "Click here if the images are for a wrong game"
6. None of the suggestions are correct.
7. Go back
8. Attempt to directly enter the game ID "5247391" in the field under the game title
9. Game images aren't pulled, even after return is pressed 

**Expected behavior**
1. Correct images for Wolfenstein: Enemy Territory are located
2. OR alternatively, entering the desired game ID in the field in images pulls that specified entry.

**Screenshots**
![Incorrect_images_pulled](https://user-images.githubusercontent.com/36831696/186352685-6cbe8b4b-5510-498d-9dda-bd646c2bb0a3.png)
![Correct_Steamgrid_page](https://user-images.githubusercontent.com/36831696/186352568-636c0a84-b109-409c-ac4b-752f8c8cd337.png)

**Desktop (please complete the following information):**
 - OS: Steam Deck
 - BoilR Version v.1.4.4
 - Launcher - executable

**Comment by PhilipK** [comment]
There is a way, and that is to manually replace the id. 
You can see the steamgriddb id in the url and you can then put that into the input field right under the game name.
If that doesn't work you can go into the config folder /home/deck/.config/boilr and edit the cache file that maps games to steamgriddb ids.

If this does not work, let me know.

**Comment by PhilipK** [comment]
I know that it is not perfect, I am working on a rewrite of the image download ui, its a bit.... basic as it is right now.

**Comment by Swizzler121** [comment]
Changing the cache fixed the issue, I think using the ID field works too, but my confusion was that it doesn't actually fetch new images until you plug in the new number, then click on an existing set image. It should probably have a button to fetch all new images (I could see an argument for not just doing that automatically if for some reason you were mixing and matching multiple steam grid entries)

**Comment by PhilipK** [comment]
Could I close this issue, and then make a new feature request to "fetch all new images"?

**Comment by Swizzler121** [comment]
Hey it's your project handle it however you wish. I'm never sure if I should be the one to close these issues or just have the maintainer do it, especially in situations like this where a resolution requires a hack like editing the cache.

**Comment by PhilipK** [comment]
In this version:
https://github.com/PhilipK/BoilR/releases/tag/v.1.4.8

There is now an option to clear all images, this lets you just run import again after fixing an image id and then everything will be auto downloaded.
