### ISSUE TITLE
Uplay games not found on Linux

### ISSUE THREAD

**Issue by deasmi** [PhilipK/BoilR#215]
**Describe the bug**
Boilr is not finding uplay games

**To Reproduce**
1. Download UplayConnectedInstaller
2. Add as non steam game
3. Run as Proton-7.0.4
4. Finish install
5. Change target to UbisoftGameLauncher.exe
6. Run UbisoftGameLauncher.exe
7. Install game
8. Run game once from launcher to ensure setup fully

**Expected behavior**
Boilr finds game and creates entries in Steam

**Desktop (please complete the following information):**
- SteamOS 3.3.1

**Additional context**
No mention of Origin at all if run from command line with flatpak run

**Comment by PhilipK** [comment]
I have not found a way to get this to work.
Uplay on Linux is therefor not currently supported.

I think it might be possible, but I will have to dedicate some time for it.

**Comment by FranjeGueje** [comment]
It's very interesting. Could it make like Origin?
I can add ubisoft games in proton with scripts but it would be grear on Boilr.

**Comment by PhilipK** [comment]
This should be solved now, in version 1.8.0
