### ISSUE TITLE
Windows Images Don't Load

### ISSUE THREAD

**Issue by sysmoon14** [PhilipK/BoilR#216]
**Describe the bug**
When choosing custom images on Windows they all say loading but never load. Thumbnails are downloaded to the filesystem but never displayed.

**To Reproduce**
1. Download latest version
2. Try to download a custom image for a non-steam game

**Expected behavior**
Thumbnails populate and you can choose one

**Desktop (please complete the following information):**
 - OS: Windows
 - BoilR Version v.1.4.5
 - Launcher (if applicable)

**Additional context**
Previous version works ok

**Comment by NightHammer1000** [comment]
Also happens for me on the Steam Deck on SteamOS

**Comment by PhilipK** [comment]
I can reproduce this bug, I will fix it asap.

**Comment by PhilipK** [comment]
This shold be solved inversion:
https://github.com/PhilipK/BoilR/releases/tag/v.1.4.7

Once someone else confirms it works for them, this issue can be closed.

**Comment by PhilipK** [comment]
I have heard others report that this fixes the problem, so I will close this.
