### ISSUE TITLE
Ability to rename game titles from the BoilR app?

### ISSUE THREAD

**Issue by Seraaron** [PhilipK/BoilR#217]
**Is your feature request related to a problem? Please describe.**
It's annoying to rename a non-steam game by going into the games properties in Steam and then typing and clicking out.

**Describe the solution you'd like**
It would be cool if we could just change the game's title as it will appear in Steam right from the BoilR app. It almost looks like this should already be possible, when you click into a game images from the parser, but the only editable text is a string of numbers which I don't understand the exact purpose of.

**Comment by PhilipK** [comment]
This will be in the next BoilR release
