### ISSUE TITLE
Unable to save images the first time after selecting

### ISSUE THREAD

**Issue by ddh** [PhilipK/BoilR#222]
**Describe the bug**
* When I select an image, the selection will be ignored. I have to select an image again for the image to "stick".
* Occasionally the application will lockup when selecting an image and I am forced to kill the application.

**To Reproduce**
1. Go to "Images"
1. Click on any game
1. Either clear an image or start with a game requiring an image
    - It can be a grid, hero, logo, icon...any of these have the symptom
1. Choose an image
1. Notice that the image does not apply.
1. Without backing out to the games list, attempt to choose the same or different image.
1. Notice that the image now applies.

**Expected behavior**
Expect to click on image once and for that selection to "stick" the first time.

**Screenshots**

https://user-images.githubusercontent.com/9056483/188243992-480aa627-4bd6-4084-9d8e-b1bd3dce89d4.mp4

**Desktop (please complete the following information):**
 - OS: Steam Deck
 - BoilR Version v.1.4.7
 - Heroic and EmuDeck

**Additional context**
* Not sure if it is related but a number of games in my list did not have grid images automatically chosen. I am having to go in manually to choose grid images, sometimes hero images, icons and logos.
* Possibly related to #189 
* Great work with BoilR btw! I love using it ❤️

**Comment by PhilipK** [comment]
Question, does it still update the image in steam?
I am wondering if this is a UI timing glitch, like it does not not update the ui, but it still does the download.

**Comment by ddh** [comment]
@PhilipK Yes, the image is still downloaded and put into the `../config/grid/` folder. It just doesn't immediately show up unless you reload the games index page or some combination of back and forth between locations.

**Comment by PhilipK** [comment]
Agreed, its bad UX, and it needs fixed. Just helps me identify what the problem is so it can be solved, thanks for reporting this.

**Comment by PhilipK** [comment]
This is solved in version:
https://github.com/PhilipK/BoilR/releases/tag/v.1.4.8
