### ISSUE TITLE
[Reminder] AUR still at 1.4.5

### ISSUE THREAD

**Issue by NikhilSaini38** [PhilipK/BoilR#223]
Hello @PhilipK, thanks for this marvelous piece of software. I use Boilr through AUR,

However, i was facing issue with online images not loading in images sub-menu. When i looked up i realized that the my AUR was at v.1.4.5, it was same upstream, while the latest version in github was 1.4.7 (in which the resolution to this issue was published)

I was able to trigger the updtae by adjusting PKGBUILD _pkgver to 1.4.7 and checksum for respective tar.gz file to d93979fc0b212b579cb5d0ba5bcf9fa54bd70ce5b6b6aa4f65614ddfe0b22db2

I would request you to update the AUR to latest so user who intend to use AUR build of Boilr may be able to do so comparatively easily.

here is the updated PKGBUILD
```
# Maintainer: Justus Tartz <aur at jrtberlin dot de>
pkgname=steam-boilr-gui
pkgver=1.4.7
pkgrel=1
_tag="v.${pkgver}"
_ver="v.${pkgver}"
pkgdesc="Synchronize games from other platforms into your Steam library"
arch=(x86_64)
license=('MIT')
url="https://github.com/PhilipK/BoilR"
makedepends=(cargo)
depends=(libx11
  libxext
  libxft
  libxinerama
  libxcursor
  libxrender
  libxfixes
  pango
  libpng
  mesa
  glu)
provides=('boilr-gui')
source=("https://github.com/PhilipK/BoilR/archive/refs/tags/${_tag}.tar.gz"
        "boilr.png"
        "boilr.desktop")
sha256sums=("d93979fc0b212b579cb5d0ba5bcf9fa54bd70ce5b6b6aa4f65614ddfe0b22db2"
            "baab109c6311f05ddbf647aa384b42098db9308c27cb50537f99bb341930387f"
            "c8e71371c9dc39db087e79d5a32df1ee0f4dd2cf5d069e38b491c3b9812d8424")

prepare() {
  cd "${srcdir}/BoilR-${_ver}"
  cargo fetch --target "$CARCH-unknown-linux-gnu"
}

build() {
  cd "${srcdir}/BoilR-${_ver}"
  cargo build --frozen --release
}

check() {
  cd "${srcdir}/BoilR-${_ver}"
  cargo test --frozen
}
```

**Comment by NikhilSaini38** [comment]
Thank you again for your efforts.

**Comment by NikhilSaini38** [comment]
Additionally, I uploaded an official [icon](https://www.steamgriddb.com/icon/20269) for "[The Dark Mod](https://www.steamgriddb.com/game/5252610)" to steamgriddb. When I try to access it from BoilR it doesn't load. I uploaded the file as .ico format. I am trying to find if the issue is with Steamgriddb API or BoilR.

I added this comment here because i am not sure if this needs a new issue ticket.

**Comment by PhilipK** [comment]
Thanks!

I will look into getting it updated (hopefully tonight. if the kids allow it)

**Comment by NikhilSaini38** [comment]
> Additionally, I uploaded an official [icon](https://www.steamgriddb.com/icon/20269) for "[The Dark Mod](https://www.steamgriddb.com/game/5252610)" to steamgriddb. When I try to access it from BoilR it doesn't load. I uploaded the file as .ico format. I am trying to find if the issue is with Steamgriddb API or BoilR.
> 
> I added this comment here because i am not sure if this needs a new issue ticket.

@PhilipK can also please help me figure this out?

**Comment by NikhilSaini38** [comment]
Also maybe this can help https://github.com/marketplace/actions/publish-aur-package

**Comment by jrtberlin** [comment]
> Thanks!
> 
> I will look into getting it updated (hopefully tonight. if the kids allow it)

AUR is now at 1.4.7

**Comment by NikhilSaini38** [comment]
thanks @jrtberlin
