### ISSUE TITLE
Itch.io game stop being detected if path is changed and changed back

### ISSUE THREAD

**Issue by DSPaul** [PhilipK/BoilR#224]
My itch.io games are no longer detected after changing the itch.io folder path to something else, and changing it back to empty. 

Seems the same as #197 where the guy fixed it by deleting a config folder, but I can't find that config folder and even if I did, there has to be a better solution to this problem.

This happened on a steam deck. I tried uninstalling and reinstalling boilr with Discover but that doesn't seem to delete the user data as all the settings such as the steamgrid API key are still there after the reinstall and as a consequence, it doesn't fix the problem.

**Comment by PhilipK** [comment]
Thanks for reporting this. I think it might be that it actually tries using the empty string instead of resetting it. I will try to look at it tonight.

I might also add a Readme of where to find the config file, you are not the only one to miss it.

**Comment by PhilipK** [comment]
This is solved in version:
https://github.com/PhilipK/BoilR/releases/tag/v.1.4.8
