### ISSUE TITLE
Uplay games for steam deck

### ISSUE THREAD

**Issue by Boba194230** [PhilipK/BoilR#255]
I have the option to import uplay games ticked but it gives an error saying that Uplay games are not supported on linux. I used the same sort of command that the origin games use linking the game's executable to the proton prefix and it works fine. I'd really like if it could be done automatically thought as it works great with origin. (Though a bit off topic, for some reason the origin section is missing one game; Star Wars Battlefront 2; and i'm not sure why because when I add it myself manually it works but boilR can't seem to find just that one)

**Comment by NightHammer1000** [comment]
Use Uplay over Lutris.

**Comment by Boba194230** [comment]
I tried but In the past those shortcuts didn’t work and I can’t actually get lutris to install uplay correctly so I manually installed it and have been linking the exes by hand

**Comment by NightHammer1000** [comment]
@Boba194230 Workaround for the Shitty Wine Bug on Lutirs can be found here:
https://github.com/flathub/net.lutris.Lutris/issues/265#issuecomment-1249398693

**Comment by PhilipK** [comment]
This should be solved in version 1.8.0
