### ISSUE TITLE
UI improvements to Images view

### ISSUE THREAD

**Issue by fpiesche** [PhilipK/BoilR#258]
I'm using BoilR to improve on custom art where Steam ROM Manager messed up the matching and I find it quite frustrating to have to scroll for miles and miles using the mouse wheel to get to where I was whenever I edit a game. I can see of several ways of improving the UI here:

* Having games listed in more than one column to reduce the amount of vertical scrolling needed.
* Being able to scroll with up/down arrow and/or pgup/pgdn
* Jumping the Images view back to the game you've just edited when going Back from the game art selection screen

Finally: having a larger blank space for games that have no art at all would be useful - maybe just an empty box the same size of the other entries, to make them more obvious in a long list of other games.

**Comment by PhilipK** [comment]
@fpiesche the newest pre-release has some ui optimizations.
https://github.com/PhilipK/BoilR/releases/tag/v.1.7.3

Would you mind trying it out and giving some feedback?

**Comment by PhilipK** [comment]
I am closing this issue, but if you disagree and there is more to improve please just comment and I will reopen it.

**Comment by fpiesche** [comment]
That's perfect! Thank you very much :)
