### ISSUE TITLE
itch games being identified wrongly

### ISSUE THREAD

**Issue by Sarume** [PhilipK/BoilR#26]
Games affected in my testcase: Underhero and HiveTime

For HiveTime a link to a non-existing file is being created: ~/.config/itch/apps/underhero/hive-time_linux_V1.2.x86_64
(The HiveTime executable isn't in the directory for the game Underhero)

This game shows up in steam as Underhero with a non-BoilR link to the non-existent executable.

For Underhero itself BoilR seems to grab the wrong executable and links to the "UnityPlayer_s.debug" file in the directory of the game (~/.config/itch/apps/underhero/Linux/)

This game shows up as Underhero as well with a normal BoilR link.

I reran BoilR several times after deleting the entries from steam itself a few times as well, deleted cache.json once (just in case it could have been interfering with it and to force a new scraping of the artwork)

**Comment by PhilipK** [comment]
Alright, i can see that Itch also stores information about stuff like those debug files, I will have to see if I can filter them out.

**Comment by PhilipK** [comment]
@Sarume can you check if this new release has fixed your problem:
https://github.com/PhilipK/BoilR/releases/tag/v.0.9.13

**Comment by PhilipK** [comment]
@Sarume the issue with duplicates should be fixed in newest version: https://github.com/PhilipK/BoilR/issues/58

The thing with unity executable is very hard for me to figure out, since itch internally seems to refer to the unity executable as well.
I might have to dig around some more in itch db to fix that one.
