### ISSUE TITLE
[Feature Request] Option to have the have all boxes unchecked by default

### ISSUE THREAD

**Issue by MehStrongBadMeh** [PhilipK/BoilR#263]
**Is your feature request related to a problem? Please describe.**
All boxes are checked in the Import Game screen, requiring me to go manually uncheck every single app that I do not want in my Steam Library, every single time I launch Boilr.

**Describe the solution you'd like**
Option to have all boxes unchecked by default, so I can choose which apps I do want to add to my Steam Library.

Bonus - if we can have the apps auto-disconnect when they are added, so I do neither need to go check them again and overwrite their art nor manually disconnect every one.

**Describe alternatives you've considered**
Having the app automatically remember which apps were unchecked and not check them again on next launch seems like it would be a reasonable alternative.

This would possibly be worth combining with a system that remembers which apps it imported and automatically skips them (appearing as the "indeterminate" check box in the list) unless clicked to force a reset of the shortcut. This would remove my need to disconnect the shortcuts.

**Additional context**
Idle thought: Pretty sure re-importing all the apps every time would result in re-downloading all the art for every app. Which seems like an unnecessary burden on SteamGridDB's bandwidth.

**Comment by PhilipK** [comment]
This is an idea that has come up before.
BoilR works by keeping track of each shortcut imported and will remove a shortcut if it is either unchecked or the game is deleted from the launcher.
I have been thinking about changing this, so that you could see what boilr was going to do instead.
Showing "theese are the shortcuts i will add, these i will not touch and these i will delete" then you could "change what it would do before it did it". 
But I only have so much spare time.

**Comment by PhilipK** [comment]
About the "re-importing all the apps every time would result in re-downloading", it does not do that, it only downloads images if they are needed/not already downloaded. Ofc, if you change the name or the exe path of a shortcut that is a new app id, and that results in boilr and steam seeing it as a new shortcut, hence a new image download.

**Comment by MehStrongBadMeh** [comment]
That's good to hear that it is not redownloading images.

That being said, would still love the ability to not have to uncheck each of the flatpak apps I don't want imported into my Steam Library every time I launch Boilr.

**Comment by PhilipK** [comment]
You can either disable flatpak totally in settings, or d if you disable a
specific game and import it will remember that choice (saves a list of all
unchecked games in its configuration file)

**Comment by MehStrongBadMeh** [comment]
Hmm, that's weird, I specifically made this issue cause it wasn't doing that for me. Let me update to the new version and try again.

**Comment by MehStrongBadMeh** [comment]
I cannot reproduce the behavior of it remembering the games are unchecked. Just tested in the latest v.1.7.5 build. Started fresh with my shortcuts by deleting all of the existing non-steam shortcuts manually, then imported everything I did want via Boilr. leaving apps I didn't want unchecked. Afterwards, if I exit and restart Boilr again, all the boxes are checked.

**Comment by PhilipK** [comment]
The newest version saves you changes, it was a bug that had snuck into the one of the latest versions.

**Comment by MehStrongBadMeh** [comment]
That did it! I guess this turned out to be more of a bug report.

**Comment by PhilipK** [comment]
Good! Can I close this issue then? Or do you still request the feature?

**Comment by MehStrongBadMeh** [comment]
Go ahead and close it as this fixed functionality perfectly matches the "alternative considered"
