### ISSUE TITLE
Cannot see games in bottles

### ISSUE THREAD

**Issue by rKsanu2MMYvypWePtQWM** [PhilipK/BoilR#268]
**Describe the bug**
It knows that bottles is installed, however it fails to locate anything

**To Reproduce**
Start BoilR thru flatpak or standalone executable

**Expected behavior**
Detect games installed thru Bottles

**Screenshots**
![Screenshot_20221029_134203](https://user-images.githubusercontent.com/35463654/198827120-91d9f483-55a7-49b7-88a7-67b002f1d97d.png)
![Screenshot_20221029_134217](https://user-images.githubusercontent.com/35463654/198827122-b02c0875-25b4-4d64-915e-de70f8374e71.png)
![Screenshot_20221029_134243](https://user-images.githubusercontent.com/35463654/198827126-df58f8ff-2514-496d-aea5-6e4779badc37.png)

**Desktop (please complete the following information):**
Steam Deck, latest flatpak version of Bottles, latest version of BoilR (tried both flatpak and standalone)

**Additional context**
none

**Comment by nerdosity** [comment]
same for me, sometimes it works, then it stops working.

**Comment by BiosElement** [comment]
If you go in and rename the Program in bottles, does it appear then? That worked for me, I just added a letter scanned with Boilr and it was found. The removed the letter, rescanned and it found it with the original name.

**Comment by BlackRabbit22** [comment]
> If you go in and rename the Program in bottles, does it appear then? That worked for me, I just added a letter scanned with Boilr and it was found. The removed the letter, rescanned and it found it with the original name.

This works however its tedious to do each time. I hope this issue gets fixed.

**Comment by PhilipK** [comment]
I have a strong feeling that this is a bottles CLI issue and not a BoilR one, with the symptoms you describe.
I will have to test it out, and if it is the case we will have to report it to Bottles.

To test it (in case someone gets time before me, which is very likely currently) you have to do the following:
* When you experience the problem run the following command in a terminal: `flatpak run --command=bottles-cli com.usebottles.bottles -j list bottles`

* Save the output.
* Then go in and do the rename.
* Run the command again.
* Save the output again
* Rename back to original name
* Run command
* Save the output
* Post result here

**Comment by nerdosity** [comment]
> If you go in and rename the Program in bottles, does it appear then? That worked for me, I just added a letter scanned with Boilr and it was found. The removed the letter, rescanned and it found it with the original name.

It worked, but it's still an issue 🤕

**Comment by flareman** [comment]
I have the exact same issue; Steam Deck on the latest stable OS, Boilr and Bottles from Discover, a couple pieces of software installed in Bottles and Boilr only sees the apps after a rename.

**Comment by Cold71** [comment]
I've been able to get around this by renaming the game, it seems like if BoilR doesn't know what it is it just gets ignored.

**Comment by Vahelnir** [comment]
> I have a strong feeling that this is a bottles CLI issue and not a BoilR one, with the symptoms you describe. I will have to test it out, and if it is the case we will have to report it to Bottles.
> 
> To test it (in case someone gets time before me, which is very likely currently) you have to do the following:
> 
> * When you experience the problem run the following command in a terminal: `flatpak run --command=bottles-cli com.usebottles.bottles -j list bottles`
> * Save the output.
> * Then go in and do the rename.
> * Run the command again.
> * Save the output again
> * Rename back to original name
> * Run command
> * Save the output
> * Post result here

I have a bottle with Ubisoft Connect, AC Valhalla and Trackmania.
Only Ubisoft Connect and AC Valhalla where shown in BoilR.

I did run `flatpak run --command=bottles-cli com.usebottles.bottles -j list bottles` on my Steam Deck:
- Before renaming Trackmania: only two entries in `External_Programs`, Ubisoft Connect and AC Valhalla.
- After renaming Trackmania: three entries in `External_Programs`, Ubisoft Connect, AC Valhalla and Trackmania.

So you were right, it looks like there is an issue on Bottles' side.
