### ISSUE TITLE
BoilR doesn't run in X11 anymore because it was ran in wayland

### ISSUE THREAD

**Issue by Keelhauled** [PhilipK/BoilR#270]
**Describe the bug**
BoilR doesn't run in X11 anymore because it was ran in wayland. The error message is:
```
The application panicked (crashed).
Message:  Failed to initialize any backend! Wayland status: NoCompositorListening X11 status: XOpenDisplayFailed
Location: /run/build/boilr/cargo/vendor/winit-0.27.2/src/platform_impl/linux/mod.rs:719
```

**To Reproduce**
1. Run BoilR in wayland
2. Run BoilR in X11
3. Error

**Expected behavior**
BoilR should have ran normally.

**Desktop (please complete the following information):**
 - OS: Steam Deck
 - BoilR 1.7.6

**Additional context**
To use wayland I ran this script from game mode.
```
unset LD_PRELOAD
exec dbus-run-session startplasma-wayland --xwayland --x11-display $DISPLAY --no-lockscreen --width 1280 --height 800 -- plasma_session
```
I could be totally wrong about this being related to wayland, but it's the only difference I can think of compared to my PC running BoilR just fine.

**Comment by PhilipK** [comment]
Does this happen for both the flatpak and standalone executable?

**Comment by Keelhauled** [comment]
It runs normally with a standalone executable

**Comment by Keelhauled** [comment]
Removing `.var/app/io.github.philipk.boilr` doesnt help either.

**Comment by PhilipK** [comment]
Uninstall and reinstall the flatpak?

**Comment by Keelhauled** [comment]
That did the trick thanks. Should I close this issue?

**Comment by PhilipK** [comment]
So I would say yes
