### ISSUE TITLE
Ubuntu 22.04 does not have libssl.so.1.1

### ISSUE THREAD

**Issue by bryanpaget** [PhilipK/BoilR#272]
Running `./linux_BoilR` on Ubuntu 22.04 results in 

```
user@ubuntu-22.04:~/$ ./linux_BoilR 
./linux_BoilR: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

This is apparently an issue with Ubuntu 22.04 in general and some users are manually installing the library. Source: https://stackoverflow.com/questions/72133316/ubuntu-22-04-libssl-so-1-1-cannot-open-shared-object-file-no-such-file-or-di.

**Comment by bryanpaget** [comment]
The Flatpak works though! :-)

**Comment by PhilipK** [comment]
This is solved in the newest release
