### ISSUE TITLE
Broken resolution on Steam Deck in gaming mode

### ISSUE THREAD

**Issue by mkaflowski** [PhilipK/BoilR#273]
The resolution of the app is broken when i run it after adding as a non steam game in game mode.
Text is super small and max mouse position is like on the picture.

https://photos.app.goo.gl/oVFEwV8uHqTc6zfc6

**Comment by danbee** [comment]
I'm seeing the same issue

**Comment by ayesc9000** [comment]
Experiencing this issue as well. It's impossible to use boilr with this issue since you can't click the import button due to the mouse problem.

**Comment by PhilipK** [comment]
This should be solved in the newest version 1.7.8
Also, if you add the --fullscreen launch argument it should use up all of the Steam Deck screen.
