### ISSUE TITLE
Does boilr have some kind of internal cache?

### ISSUE THREAD

**Issue by Wibbbs** [PhilipK/BoilR#274]
Just wondering if boilr uses some kind of internal cache?

I wanted a specific image for a certain game that wasn’t on steamgriddb,  so I logged in and uploaded the image myself. I can see the image on the steamgriddb website, but it doesn’t show up in boilr for that game. Is there any kind of cache I need to clear for it to re pull the images from the steam grid api?

I am not sure how to call the api myself to see if the api is just not returning the image.

**Comment by PhilipK** [comment]
BoilR does have cache of thumbnails, not search results. So it might be that it just takes a while for steamgriddb to update the API.
