### ISSUE TITLE
I cannot open BoilR. (Nobara 36)

### ISSUE THREAD

**Issue by noemsus** [PhilipK/BoilR#275]
**Describe the bug**
I cannot open BoilR with Flatpak or with normal one.

**To Reproduce**
Idk just use Nobara 36 GNOME.

**Expected behavior**
It should open and popup, but it doesn't do anything.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Nobara Linux 36
 - BoilR Version [e.g. v.1.4.5]
 - Launcher Heroic

**Comment by noemsus** [comment]
nvm

**Comment by PhilipK** [comment]
What was the problem?
