### ISSUE TITLE
Flatpak BoilR Can't Find Flatpak Games on Deck

### ISSUE THREAD

**Issue by InklingGirl** [PhilipK/BoilR#277]
**Describe the bug**
The Flatpak version of BoilR can't find the Flatpak games I have installed on my Steam Deck, namely _Super Tux Kart_.

**To Reproduce**
1. Go to Import Games
2. Be met w/ 'Failed finding games' w/ hover text reading:
`Error message: No such file or directory (os error 2)`

**Expected behavior**
For it to find Super Tux Kart for me to import.

**Desktop (please complete the following information):**
 - OS: Steam Deck
 - BoilR Version: 1.7.6

**Comment by InklingGirl** [comment]
>Have you tried renaming

I'm not sure what you mean @PhilipK.

**Comment by InklingGirl** [comment]
May you please clarify what you meant? Thank you.

**Comment by PhilipK** [comment]
It might be fixed now, if you update bottles:
https://github.com/bottlesdevs/Bottles/issues/2307

I have not seen this bug myself, but a workaround should be to go into bottles, rename the bottle that BoilR does not find, and rename it back to the original name again.

**Comment by PhilipK** [comment]
This is solved in the newest version (it might take a couple of hours for it to be published on flatpak)

**Comment by InklingGirl** [comment]
Can confirm this is now fixed. Thank you @PhilipK for helpfully addressing this! The only thing I'll note, although off-topic, is I did have to change the _Steam user id:_ from '0' (the default) to the longer string of numbers listed in order for image changes to take effect, but otherwise am having no issues. Useful software.
