### ISSUE TITLE
Boilr not recognizing games installed on Epic Games Launcher

### ISSUE THREAD

**Issue by thelaif** [PhilipK/BoilR#279]
**Describe the bug**
Title. Boilrdoesn't list any games I have listed on Epic. (I have Tony Hawk Pro Skater 1+2)

**To Reproduce**
1. Install Epic Launcher
2. Install Game (Tony Hawk Pro Skater 1+2)
3. Download native Boilr from Github
4. Run Executable
5. Epic Games lists no games available for import.

**Expected behavior**
Boilr to detect Epic Games titles and import them.

**Desktop (please complete the following information):**
 - OS: Steam Deck
 - BoilR Version latest from release page
 - Epic Games Launcher

**Additional context**
Tried switching to Boilr flatpak, didn't work. Tried switching Proton versions for Epic, didn't work.

**Comment by vkbsb** [comment]
I'm seeing the same issue. I've installed EGS and have installed couple of games, but running boilr doesn't detect these games.

**Comment by vkbsb** [comment]
@PhilipK  thought ill' share the fix for the EGS games not getting picked up by the tool. Please review and merge. 
Thank you

**Comment by PhilipK** [comment]
This should be solved in the newest version, thanks to @vkbsb
