### ISSUE TITLE
Include non-installed titles from other launchers

### ISSUE THREAD

**Issue by Willdrick** [PhilipK/BoilR#290]
Boilr makes it easy to see all your installed games in one place (steam). But sometimes it'd be nice to be able to have not just that, but all the available/bought games listed too.

I'm not really sure how feasible this is, but it would be useful if Boilr could add all games from other launchers (i.e. Heroic, Lutris, Itch, on Linux) as Steam shortcuts, just like it does with regular installed games.

It'd require a bit of extra maintenance by the user, but it could be a nice feature to have all available games listed right on steam, even better with the ability to import them as a separate category

**Comment by PhilipK** [comment]
The big "problem" with this feature is that it would require integrating with a bunch of apis.
Finding the games that are installed, that usually requires finding some kind of config file that mentions where the games are.
Finding all available games requires setting up authentication, api integration, calling some rest services if you are lucky and cookie hacking if you are unlucky.

I really wish that it would be easy/possible to do, but it is such a huge undertaking that I simply don't have the time to do it or the free free time to maintain it.

**Comment by Willdrick** [comment]
Fair enough, yeah I was thinking about that while I was writing the issue (that's why I used "not sure how feasible this is"). I'll have to dig around and see if there's a way into tricking Legendary to dummy-installing all games (without actually installing them). Maybe there's a way of pulling that info straight from lutris/legendary without Boilr needing to interact directly with the services (EGS/GOG/et al).

**Comment by NightHammer1000** [comment]
I think you are Looking for Playnite here. That does what you want. You can import Games that are not Installed into the Library.
We would just need Playnite Support in BoilR. Would be totaly awesome.

Currently solving that with a Playnite Addon that creates Shortcuts for all Games except Steam itself in the Library to a Folder and then Using Steam ROM Manager to Import all these into Steam. Very Cumbersome. But it at least works.

**Comment by PhilipK** [comment]
Alright, using Playnite and setting up all games there, and THEN importing it with BoilR now does what you want @Willdrick

**Comment by Willdrick** [comment]
Sorry I didn't ping back. As far as I can see Playnite is windows-only so I'm kinda SOL. For now I've added all my accounts to Lutris and I'm using that to browse for my non-installed games, though it's not ideal, it's better than having to launch different programs looking for a specific game I might want to install at the time.
