### ISSUE TITLE
Does not start anymore since Release v.1.7.8 on the Steam Deck

### ISSUE THREAD

**Issue by NightHammer1000** [PhilipK/BoilR#292]
Cant get it to run on Steam Deck since 1.7.8

There is no Console output, so I have no Idea whats going on.

**Comment by PhilipK** [comment]
Is this flatpak or native?

**Comment by PhilipK** [comment]
Well, I think its the native version, looks like openssl is missing on newest version (and in newest steam os version). Will have to include it statically.

**Comment by BlackRabbit22** [comment]
Yes, its openssl and its the native version. 
Here is the full error:

```
error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
```

**Comment by PhilipK** [comment]
Thanks @BlackRabbit22 just got that exact error that on my own deck as well.
New version should be out in a couple of minutes.

**Comment by PhilipK** [comment]
Sorry about releasing something that does not even run on the Deck.
Plus side, I have now found a way to use distrobox to develop BoilR on the deck itself, which simplifies development and testing a whole lot!

**Comment by NightHammer1000** [comment]
@PhilipK 
If you find a way to start Apps installed in Distrobox from GamePadUI Directly let me know.
Fighting with it for DAYS now.

Thanks for the quick fix, btw.

**Comment by PhilipK** [comment]
Solved in this release:
https://github.com/PhilipK/BoilR/releases/tag/v.1.7.12

**Comment by rauldipeas** [comment]
The latest version of BoilR (1.7.17) it's not opening here too.

Kubuntu 22.04 running the binary version of BoilR on X11.

https://user-images.githubusercontent.com/12108031/210357289-79b665f7-52bc-4990-9d22-70858c78f724.mp4

**Comment by rauldipeas** [comment]
The log from terminal.

![Screenshot_20230103_093153](https://user-images.githubusercontent.com/12108031/210357879-a452a291-f8db-462a-a50b-9f9c69c7d199.png)

**Comment by PhilipK** [comment]
@rauldipeas can you open a new issue that is specific for kubuntu 22.04, since this one is about steam deck?
