### ISSUE TITLE
Current UI too big for Steam Deck screen

### ISSUE THREAD

**Issue by walllable** [PhilipK/BoilR#30]
I can't see the bottom of the application on the Deck's native resolution, 1280x800. Maybe add a scroll bar or something?

![image](https://user-images.githubusercontent.com/10066958/158011151-755f2b17-0f95-4c98-a95e-6e6d2fe53d44.png)

**Comment by marmite22** [comment]
Not a fix, but a quick work around I figured out - you can change the orientation of the Deck's screen to portrait in Display Settings which gives enough height to see the whole UI.

**Comment by PhilipK** [comment]
I am working on making the current design smaller, it should be ready in less than an hour. 

But in the long run, I think it would be great with a Deck specific UI version.

**Comment by PhilipK** [comment]
This has now been solved in this release:

https://github.com/PhilipK/BoilR/releases/tag/v.0.9.7
