### ISSUE TITLE
Selecting Images and then Steam ID no longer works on Steam Deck, it crashes

### ISSUE THREAD

**Issue by moraroy** [PhilipK/BoilR#315]
**Describe the bug**
Both Linux version and windows version crash on Steam deck after selecting Images and Steam ID.
**To Reproduce**
1. Go to 'Images'
2. Click on 'Steam User ID'
3. Scroll down to 'desired ID'
4.Crashes

 - OS: [Steam Deck]
 - BoilR Version [e.g. v.1.7.19]
 - Launcher (if applicable)

**Comment by PhilipK** [comment]
@moraroy can you try to share the terminal output? 
Both the native and flatpak on steam deck ?

**Comment by moraroy** [comment]
@PhilipK 	Could not load platform amazon, gave error: Unknown platform named amazon
Could not load platform playnite, gave error: Unknown platform named playnite
The application panicked (crashed).
Message:  called `Option::unwrap()` on a `None` value
Location: src/ui/components/game_image_button.rs:127

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

**Comment by PhilipK** [comment]
Thanks. I will have to fix it after work.

**Comment by PhilipK** [comment]
Weird, it does not fail on my steamdeck, but I can see where the bug might be, so i will have to work on that this evening.

**Comment by moraroy** [comment]
It may have to do with mine, I've been moving along of folders around maybe I caused an error in my steam id

**Comment by PhilipK** [comment]
I have a feeling that it is because it can't find your steam folders.
Currently I am getting rid of all the places that I made some assumptions
(unwrap) about user setup that could cause this crash.
But you could try to backup your boilr config file and then delte it. It's
found in /home/deck/.config/boilr

**Comment by moraroy** [comment]
I deleted the configuration file, and loaded the Linux version back up, re did some of my settings but selecting the steam Id still crashes... one thing I noticed though..


if I select "images" then on the right drop down box select "images for steam games" 

Then click on the left drop down box and select "steam ID" it doesn't crash. 

It only crashes when "steam ID" is selected and "Images For Shortcuts"

**Comment by PhilipK** [comment]
@moraroy I made a prerelease here:
https://github.com/PhilipK/BoilR/releases/tag/v.1.7.20

It fixes a bunch of possible crashes (it should be almost impossible to crash now).
Can you check if it helps?

**Comment by moraroy** [comment]
You fixed it brother! Nice work. No more crashes on both the Linux version and Windows! I like how "0" is longer there it just goes straight to your ID.

**Comment by moraroy** [comment]
@PhilipK

**Comment by PhilipK** [comment]
Super! I will make it an official release, hopefully by tomorrow (after some more testing, but mainly after all 3 kids are asleep :-) )

**Comment by PhilipK** [comment]
Alright, its released, thanks for reporting this
