### ISSUE TITLE
Cannot Find Custom Playnite Install

### ISSUE THREAD

**Issue by Blootrix** [PhilipK/BoilR#323]
I have Playnite installed to a custom folder outside of the original programmed path and Boilr is not detecting it, even if I try to select it as a portable install and direct it to the folder it's installed in, any idea why?

PS: Adding support for uninstalled games through Playnite was a huge brain move, cannot wait to get it working!

**Comment by NightHammer1000** [comment]
You have to specifiy the Path to the Desktop exe in the Path for the Portable Instance. Not the folder.
Then it works.

**Comment by Blootrix** [comment]
> You have to specifiy the Path to the Desktop exe in the Path for the Portable Instance. Not the folder. Then it works.

I've tried:
"C:\Users\Bloo\Games\Playnite\Playnite.DesktopApp.exe"
C:\Users\Bloo\Games\Playnite\Playnite.DesktopApp.exe
C:\Users\Bloo\Games\Playnite\
C:\Users\Bloo\Games\Playnite\

None have worked.
"Import from Playnite" & "Use Playnite Portable Version" are both ticked.
Program restarted between each attempt.

**Comment by NightHammer1000** [comment]
Playnite has to be closed. Thats another point.

**Comment by PhilipK** [comment]
@Blootrix could you upload your games.db file?
Might be that the parser is not able to find the games in it for some reason, but hard to know without the db file.

**Comment by PhilipK** [comment]
@Blootrix I think that it should be possible to give a better error message if playnite is still open (since it always gives the same error message)

**Comment by NightHammer1000** [comment]
Yeah. It throws a Access Denied.

**Comment by Deevian** [comment]
Ran into this just now, the solution was a mix of all of the above, along with an extra step.

Essentially — my library wasn't in the same folder as the `Playnite.DesktopApp.exe`, it was in `AppData\Roaming\Playnite` instead. The solution was to:

- Shut down Playnite
- Move the `library` folder to the folder where I had my portable Playnite installation
- Turn on Playnite, open `Settings` > `Advanced`, and update the `Database Location` to the new location

This is how the it looks like in the config now:

```
portable_launcher_path = "C:\\Games\\Playnite\\Playnite.DesktopApp.exe"
```

It would be useful to have a separate field for the library location for situations like these 😄
