### ISSUE TITLE
Game Pass

### ISSUE THREAD

**Issue by AngelAbaddon** [PhilipK/BoilR#327]
It seems there's been a recent change to GP folder permissions for games that have user accessible folders. It's now possible to add Game Pass games directly to Steam via the gamelaunchhelper.exe found in *Game Folder*/Content - previously this would flag up as denied due to folder permissions. With this change, is GP integration now possible?

**Comment by scyto** [comment]
it should be possible given that uwphook has been doing this for quite some time, i would love to see this in BoilR
https://briano.dev/UWPHook/

**Comment by BitGrub** [comment]
steamsync can do this really well. Some games (Sunset Overdrive) aren't picked up (probably because of old GP install method), but for the most part it works

**Comment by PhilipK** [comment]
Hi thanks for bringing this to my attention, don't know how I overlooked this post.

I will look into how some of the other tools do it and then hopefully have time to implement it in boilr as well.

**Comment by PhilipK** [comment]
I have this working locally now:
https://github.com/PhilipK/BoilR/pull/350

I will make a pre-release of this and hope that someone will test if it also works for them.

**Comment by PhilipK** [comment]
Game Pass is now implemented:

https://github.com/PhilipK/BoilR/releases/tag/v.1.9.0

Let me know how it works out for you.
