### ISSUE TITLE
MiniGalaxy Support

### ISSUE THREAD

**Issue by EzioTheDeadPoet** [PhilipK/BoilR#34]
Hi so I have an issue with getting GOG Galaxy to work through Lutris, it just doesn't want to launch at all. But there is this launcher called MiniGalaxy that works wonders installing native Linux games even if they don't work with any other option like Lutris(At least Hyper Light Drifter only works for me on the steam deck with minigalaxy)

So adding support for mini galaxy would be amazing as it sadly doesn't add shotcuts to the start menu or anything.

**Comment by PhilipK** [comment]
I did not know about that one, it looks neat, and it is open-source https://github.com/sharkwouter/minigalaxy it should be doable, I will look into it.

**Comment by isopix** [comment]
I prefer GameHub (supports GoG, Steam, HumbleBundle, Itch.io):
https://github.com/tkashkin/GameHub
and there's fork with EGS support:
git+https://github.com/Lucki/GameHub.git#branch=epic
What I like in gamehub is seamless support for GamePads in interface (shows gamepad buttons on buttons in UI, when using gamepad)

But if you are interested in command line, there's LGOGDownloader (served as backend for many clients in the past):
https://github.com/Sude-/lgogdownloader
It uses official GOG Galaxy API, is WTFPL and is widely used by PKGBUILDs in ArchLinux's AUR.

another command line is wyvern):
https://git.sr.ht/%7Enicohman/wyvern/

 - - -

About Epic/EGS, Heroic is nearly 500MB bloatware. There's (much more popular in the past, serving also as backend) legendary
https://github.com/derrod/legendary

There's also fulll-features, 5MB "Rare" client:
https://github.com/Dummerle/Rare

**Comment by EzioTheDeadPoet** [comment]
> I prefer GameHub (supports GoG, Steam, HumbleBundle, Itch.io):
> https://github.com/tkashkin/GameHub
> and there's fork with EGS support:
> git+https://github.com/Lucki/GameHub.git#branch=epic
> What I like in gamehub is seamless support for GamePads in interface (shows gamepad buttons on buttons in UI, when using gamepad)

Is GameHub available on flathub as a flatpack ? Cause if not then it is of 0 use to anyone with a steam deck.

> About Epic/EGS, Heroic is nearly 500MB bloatware. There's (much more popular in the past, serving also as backend) legendary
> https://github.com/derrod/legendary
> 
> There's also fulll-features, 5MB "Rare" client:
> https://github.com/Dummerle/Rare
> 

I enjoy having a GUI to browse my games, so does this Rare client offer a GUI that can do that and is it available as a flatpack on flathub ?

**Comment by isopix** [comment]
Yes, Gamehub is available as flatpak in download section of Gamehub's
Github. (unfortunately you cannot install it from Discover on
SteamDeck and must use command line)

**Comment by isopix** [comment]
Using MiniGalaxy on SteamDeck is a nightmare:
 - it doesn't support gamepad/SteamInput
 - it doesn't work in GameMode
 - it's very buggy about windows games installation on SteamDeck (there are missing some components, like InnoExtract,, but sometimes it instals[while usually fails], and often after "uninstalling" game, it still appears there, after reopening MiniGalaxy

GameHub:
 - works in GameMode(a bit blurry, but usable)
 - wonderfully supports SteamInput, like 1st tier games, with proper buttons lables(only when joypad detected)
 - last bug was eliminated half year ago

It doesn't change the fact that GameHub's flatpak is broken, and author knows that and searches for knowledgable person to fix it.

Anyway currently your app is totally unusable on SteamDeck for GOG.
And for custom shortcuts it fetches wrong pictures in 90% of cases, and 25% of it is some lesbian-themed games or i.e. for logical game "Enigma" it fetched "Hentai IQ Enigma".
And this are apps like Enigma, Gcompris, etc, I've installed for kids ;-)

**Comment by PhilipK** [comment]
@isopix I am surprised that you are seeing wrong games in 90% cases, that is not what I have experienced or what I have heard other people report. Are those numbers actually what you experience or  to make a point? 

Eventually I will get around to making it possible to select covers inside BoilR, but for now, the workaround is to set a custom image manually and then BoilR won't overwrite it. The problem is that I use the search function from SteamGridDB, and it "guesses" incorrect, and ther is no real way that I can know what the real game was supposed to be.

**Comment by isopix** [comment]
But it's all out-of-stores apps/games (usually installed by package managers)

I wonder if it's possible to filter out all this 'adult' crap, because for some reason it's mostly it.

**Comment by PhilipK** [comment]
https://github.com/PhilipK/BoilR/releases/tag/v.0.9.18

Well this should help. I can't filter out nsfw on the game search, but I can on the image search.

**Comment by EzioTheDeadPoet** [comment]
> Using MiniGalaxy on SteamDeck is a nightmare:
>  - it doesn't support gamepad/SteamInput
>  - it doesn't work in GameMode
>  - it's very buggy about windows games installation on SteamDeck (there are missing some components, like InnoExtract,, but sometimes it instals[while usually fails], and often after "uninstalling" game, it still appears there, after reopening MiniGalaxy

All points why I would love support for detecting native Linux games installed with it so you can skip it for launching them. Because no other gog alternative I tried was able to install Hyper Light Drifter in a way that I can run it. I haven't had time to try out GameHub yet, but if the flatpack is broken then I can't anyway.

**Comment by isopix** [comment]
GameHub has generally much better support (and much more settings) for
windows games (you can choose between InnoExtract and native
installer, etc. It has built-in workarounds for some
games/installers). If it only would have proper flatpak....

**Comment by isopix** [comment]
> https://github.com/PhilipK/BoilR/releases/tag/v.0.9.18
> 
> Well this should help. I can't filter out nsfw on the game search, but I can on the image search.

It has genuinely helped. Only one app with teasing lesbians in underwear were left(for sound recorder) and one with satanism symbolism ^^
I don't know if you own SteamDeck, but it's annoying that all you see are pidctures(no titles), so if  it fetched incorrect ones, then you don't know what's behind, until you start it/

**Comment by DieKatzchen** [comment]
I also would like GameHub support. The itch.io app won't install Windows games on Linux, but GameHub will. Unfortunately while the Linux games it installs are easily located by BoilR (and by the itch.io app, although it can't actually launch them), BoilR doesn't see the windows games.

**Comment by isopix** [comment]
Thanks.

BTW, are you currently working on adding support for ANY native linux
GOG client?
I would switch immediately to it, because would like to use Boil at all.

**Comment by PhilipK** [comment]
https://github.com/PhilipK/BoilR/releases/tag/v.1.7.0 now supports minigalaxy
