### ISSUE TITLE
BoilR Not Working in Flatpak

### ISSUE THREAD

**Issue by SJPBP** [PhilipK/BoilR#345]
When I run 
" flatpak run io.github.philipk.boilr " in the terminal I get these errors:
Could not load platform amazon, gave error: Unknown platform named amazon
Could not load platform playnite, gave error: Unknown platform named playnite
wl_surface@20: error 2: Buffer size (1556x45) must be an integer multiple of the buffer_scale (2).

**Comment by SJPBP** [comment]
I used a flatseal to remove Wayland windowing system access, which solved my problem

**Comment by PhilipK** [comment]
Which kind of OS / setup is this?
