### ISSUE TITLE
Missing Game Pass titles

### ISSUE THREAD

**Issue by AngelAbaddon** [PhilipK/BoilR#351]
Thanks for the Game Pass implementation, looks to be a solid start, but on testing I've found the following games not being picked up to import:

Atomic Hearts
Back 4 Blood
Battletoads
Blazblue Cross Tag Battletoads
Chorus
Crackdown 3*
Dreamscaper
Everspace 2
Forza Horizon 5
Frostpunk*
Gears 5
Gears Tactics
Ghostwire Tokyo
Guilty Gear Strive
The Gunk
Halo Infinite
Halo MCC
Hellblade
Hi-Fi Rush
High on Life
Last Call BBS
MS Flight Simulator
Neon Abyss
The Outer Worlds
Outriders
Persona 5 Royal
Redfall
Sunset Overdrive*
TMNT Shredders Revenge
Trek to Yomi
Weird West
Wolfenstein Youngblood
Wreckfest

The * are one's on the old file format system so may not work regardless depending on how it pulls the games, but the others all use the new accessible file format and aren't all that different to the one's that did import.

**Comment by PhilipK** [comment]
Thanks for the heads up. I will try to debug why those do not work.

How many worked? How many percent?

**Comment by PhilipK** [comment]
I can recreate this problem and i think i know why it is happening, will look at it as soon as I have time

**Comment by PhilipK** [comment]
This new version should find the games. I did not have the hdd space to test all of those, but the ones i did test worked now.

https://github.com/PhilipK/BoilR/releases/tag/v.1.9.1
