### ISSUE TITLE
Release 1.9.0 gets detected by WD.

### ISSUE THREAD

**Issue by Evonos** [PhilipK/BoilR#352]
WD detects it as Trojan:Win32/Wacatac.B!ml

While i know this app is safe , you might want to upload it to WD / microsoft as safe.

https://i.imgur.com/Go9CfkD.png

**Comment by NightHammer1000** [comment]
Wacatac.B!ml is the Typical False Positive Windows throws. Whenever I see a False Positive its that one.

**Comment by PhilipK** [comment]
The problem here might be that the exe is compressed, could be that WD has
a hard time figuring it out. I will try to upload an uncompressed version
and see what happens

**Comment by Evonos** [comment]
> Wacatac.B!ml is the Typical False Positive Windows throws. Whenever I see a False Positive its that one.

Ye i know as i said.
but The dev might want to Submit their releases here as safe.
https://www.microsoft.com/en-us/wdsi/filesubmission?persona=HomeUser

**Comment by PhilipK** [comment]
I have submittet it, thanks for pointing it out to me.

**Comment by PhilipK** [comment]
Microsoft agrees, it is not malware :-)
https://www.microsoft.com/en-us/wdsi/submission/9d4a9a31-b266-40fa-9ec9-ca723c789591
