### ISSUE TITLE
Doesn't work with multiple users

### ISSUE THREAD

**Issue by renssies** [PhilipK/BoilR#37]
When multiple users are present on the machine it will pick the user with the lowest user ID and add the games to that account.
I don't see a way to specify a user, so I'm assuming this functionality doesn't exist.

I'm using it on Steam Deck, but you can test it on steamOS and Big Picture on Windows also has a multi user mode if I remember correctly.

**Comment by PhilipK** [comment]
Do you have an example of what BoilR prints when you have multiple accounts.
On pc if tuy have multiple accounts logged in BoilR picks it up, so I wonder if they have changed it with steam os

**Comment by renssies** [comment]
You are correct, the konsole output does give me for both users. And I couldn't replicate the tool adding it to only one account. 

So I'm assuming it was a PEBKAC, or should I say PEBSDAC (Problem exists between Steam Deck and chair)
