### ISSUE TITLE
Lutris "Did not find any games"  on recent update Boilr (1.9.2)

### ISSUE THREAD

**Issue by goofedup** [PhilipK/BoilR#371]
As title states after updating to 1.9.2 Boilr isn't finding any games under Lutris.

 - OS: Steam Deck
 - BoilR Version 1.9.2

**Comment by goofedup** [comment]
Just wanted to confirm this is definitely related version 1.9.2. When downgrading to 1.9.1 everything works and games are found under Lutris.

**Comment by PhilipK** [comment]
thanks for the report, just to make sure, is this with Lutris through flatpak or direct install? (I am assuming flatpak)

**Comment by goofedup** [comment]
> thanks for the report, just to make sure, is this with Lutris through flatpak or direct install? (I am assuming flatpak)

flatpak

**Comment by PhilipK** [comment]
I have made a pre-release. It should solve the problem, can you confirm?
https://github.com/PhilipK/BoilR/releases/tag/v.1.9.3

(give it a couple of minutes to finish building, after I have posted this, the files should show up)

**Comment by goofedup** [comment]
> I have made a pre-release. It should solve the problem, can you confirm? https://github.com/PhilipK/BoilR/releases/tag/v.1.9.3
> 
> (give it a couple of minutes to finish building, after I have posted this, the files should show up)

The pre-release v.1.9.3 doesn't find any games in Lutris. I retested v.1.9.1 again just to confirm it works and it still does. If there's anything else I can send you to help figure things out let me know. It seems currently I'm the only one who is experiencing this issue so maybe it's something on my end? No idea. I'll just stick with v.1.9.1 for now.

**Comment by PhilipK** [comment]
Which version of lutris do you have?

**Comment by PhilipK** [comment]
Also there is a new setting for in boilr to only include games that are
installed or not, is it in or off for you?

**Comment by goofedup** [comment]
> Which version of lutris do you have?
0.5.13

Search installed only was checked. I unchecked it and tried importing and same result. On or off both have the same result of did not find any games.

**Comment by culain-45124** [comment]
So sorry, this is my fault. I should have been clearer in my PR that this wouldn't work until a new version of Lutris is released as the new `-a` CLI option won't be present in the flatpak until then so queries will fail.

**Comment by PhilipK** [comment]
I tried to fix it in 1.9.3 where it just reverts to its old ways when "only
installed" is on. But it does not seem to work for some...

**Comment by PhilipK** [comment]
@culain-45124 could I get you to test 1.93

**Comment by culain-45124** [comment]
Yeah of course, I'll have a look this evening.

**Comment by culain-45124** [comment]
Think I've found the issue in line 16 of `src/platforms/lutris/lutris_game.rs`. The `details` field isn't part of the original `-ol` json return.

I'll just test this and get a PR in, but feel free to beat me to it. Everything is grinding to a halt here
