### ISSUE TITLE
Setting for platform Lutris are invalid, reason: program not found

### ISSUE THREAD

**Issue by Squazz** [PhilipK/BoilR#41]
Using Windows GUI version, I'm getting this message in the command-prompt: "Setting for platform Lutris are invalid, reason: program not found"

I'm not sure if it has any tangible effect, but I'm unable to disable Lutris in the GUI, in order to make the error-message disappear

**Comment by PhilipK** [comment]
You are right, I forgot to add Lutris to the ui. It is included in this commit, https://github.com/PhilipK/BoilR/commit/1f9d18c43aa73753171859184c4c59484fe855ac , it will be included in the next release.

Thanks for posting the bug!

**Comment by PhilipK** [comment]
Fixed in the newest release
