### ISSUE TITLE
Rocket League on Heroic won't launch from Steam

### ISSUE THREAD

**Issue by kuynh** [PhilipK/BoilR#50]
Downloaded rocket league on heroic and when launching it from desktop mode seemed to work fine. However, when boilr made a launch app for it within steam, it would not launch. It would look like its launching for a second then revert back to steam library. Within the boilr UI, legendary and heroic are checked if that matters. Boilr for itch.io games works perfect though so thanks for that.

**Comment by PhilipK** [comment]
Others have confirmed that the newest version works on steam deck now (if you select a proton version for the game), so I will close this issue.
If it does not work for you , we can reopen the issue.

**Comment by PhilipK** [comment]
There seems to still be a problem with specificly Rocket League

**Comment by PhilipK** [comment]
In version https://github.com/PhilipK/BoilR/releases/tag/v.1.3.9 I have added an option to launch games through the heroic launcher, if you select Rocket League in settings to be launched that way it should fix this issue. I will close this issue, but if it does not help you, let me know and I will re-open this.
