### ISSUE TITLE
RARE (5MB Epic/EGS Client written in Qt) support

### ISSUE THREAD

**Issue by isopix** [PhilipK/BoilR#56]
There's also fulll-featured "Rare" client:
https://github.com/Dummerle/Rare

It's uses Qt and takes 5MB on HDD (vs 480M for Heroic bloatware)

**Comment by PhilipK** [comment]
It should work, if you enable the legendary integration in BoilR.
I can try it out later.

**Comment by isopix** [comment]
Thanks, BTW Dummerle replied to me:

"Flatpak will be supported with the next major release. I have some
test files ready, but the code needs some fixes, to support flatpak.

I probably will create a test release, with flatpak support. Some
features are planned or in progress for the next release, so it takes
a little time"
https://github.com/Dummerle/Rare/issues/192

**Comment by PhilipK** [comment]
Maybe I should get in touch with the Rare developer, since Heroic ended up not using the "default" legendary installation when they went flatpak. If Rare does the same thing I might have to do some fixes to make sure that boilr uses the legendary they use.

**Comment by PhilipK** [comment]
Side note, if you are very concise about disk space, you can set things up with the UI version of BoilR , click save settings and then run the cli version from there. The UI version is 5 mb and the cli 1 mb, mainly because I have not been able to get executable compression to work on the ui version on linux.

**Comment by PhilipK** [comment]
I have  remove  BloatWare from this issues title. While it is true that it is a 100x difference in disk size, it is a tradeoff that the Heroic devs made, to use electron. I would not make the same choice for BoilR, but we don't have to put them down to raise others up.

**Comment by PhilipK** [comment]
I just testet this, and it works out of the box, i will update the readme and ui to reflect this.
In short, as expected since Rare uses legendary BoilR picks up the game right away.
