### ISSUE TITLE
Error Synching

### ISSUE THREAD

**Issue by kuynh** [PhilipK/BoilR#61]
Setting for platform Legendary are invalid, reason: No such file or directory (os error 2)
Found 4 game(s) for platform Itch
Setting for platform Lutris are invalid, reason: No such file or directory (os error 2)
Found 1 game(s) for platform Heroic
Found 2 user(s)
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: Empty }', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/steam_shortcuts_util-1.1.4/src/shortcuts_parser.rs:206:47
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

This is what the console outputs when running the script.

**Comment by PhilipK** [comment]
Which os is this on?

**Comment by kuynh** [comment]
Steam deck os

**Comment by PhilipK** [comment]
Hmm, this happens when BoilR can not parse the shortcut list you already have.
Specificly when it the order number that is supposed to be a number is actually not a number.
Did you add any other 3rd party games yourself? Did you use another tool?

**Comment by PhilipK** [comment]
@kuynh can you try the newest version, it should help:
https://github.com/PhilipK/BoilR/releases/tag/v.0.9.19

**Comment by kuynh** [comment]
Yes, I used heroic bash launcher to check it out. I will try out this new version once I get the chance.

**Comment by kuynh** [comment]
That fixed it thank you.
