### ISSUE TITLE
Heroic/Epic/Flatpack - Some games creating duplicate shortcuts

### ISSUE THREAD

**Issue by marmite22** [PhilipK/BoilR#65]
Using v.0.9.22 of BoilR

Some games seem to be creating two shortcuts. Others are not.

I deleted all the shortcuts created by previous runs. Ran UI sync. Restarted Steam.

Hades and Rocket Legue created 2 shortcuts.
Chicory, Horace, PikuNiku and Superbrothers Sword and Sworcery just created 1.

Interestingly A Short Hike was creating 2 shortcuts. I uninstalled it through Heroic, deleted both shortcuts and then ran BoilR again and it has created just one shortcut. The shortcut points to /home/deck/games/Heroic/AShortHike/AShortHike.exe but I browsed to that directory and that .exe doesn't exist. There is a file AShortHike.dxvk-cache in there but that's it.

**Comment by PhilipK** [comment]
@marmite22 you know the drill by now :-) There is a new release:
https://github.com/PhilipK/BoilR/releases/tag/v.0.9.23

Can you test if it works?

**Comment by marmite22** [comment]
A short hike (uninstalled) is still showing up (it also appears in cache.json if that makes a difference - perhaps I need to remove it from there?)

Rocket League and Hades only show up once now!

**Comment by PhilipK** [comment]
Did you install and then delete a short hike?

**Comment by marmite22** [comment]
I believe the order of events was
Installed Short Hike via heroic/epic
Ran BoilR (not sure which version) and it added 2 shortcuts
Uninstalled Short Hike
Deleted the shortcuts from steam manually
Ran latest BoilR and 1 shortcut came back.

**Comment by PhilipK** [comment]
That is the problem, I have to check if the game is actually still installed (if the file exsists). It will be fixed in the next release.

**Comment by PhilipK** [comment]
Version https://github.com/PhilipK/BoilR/releases/tag/v.0.9.24 should fix it

**Comment by marmite22** [comment]
It's gone! Thanks so much.
