### ISSUE TITLE
Feature Request - Don't require Steam Restart after adding shortcuts

### ISSUE THREAD

**Issue by marmite22** [PhilipK/BoilR#67]
This might well just be a limitation of Steam or whatever method you are using to add shortcuts to it, but it would be cool if you could some how refresh the Steam library after syncing without having to exit and re-open Steam.

Feel free to close if this isn't possible.

**Comment by PhilipK** [comment]
I would love to make this. But I don't think that it is possible to do, because Steam only checks the shortcut file on startup.
One idea is to make an option for BoilR to kill steam and start it again on sync. It would have to be a option , since I don't know if it is something everyone would want.

**Comment by marmite22** [comment]
Perhaps a "Restart Steam" button next to the Sync button that appears after sync is complete. If not a button, then at least a message telling people to do it to help out noobs.

**Comment by PhilipK** [comment]
There is now an option to restart steam on synch. I guess it helps on this issue?

**Comment by marmite22** [comment]
I think that solves it unless someone discovers some way to force Steam to re-check the shortcut file. Thanks again for your work on this.
