### ISSUE TITLE
Itch problems 

### ISSUE THREAD

**Issue by Squazz** [PhilipK/BoilR#70]
v.0.9.24 - Windows UI

This new version where icons are preferred to BigPicture is nice! 👍 

But, I keep having problems with icons for games from itch
![image](https://user-images.githubusercontent.com/1504055/161394712-3f4da288-3bf6-463b-b2a8-bc6bd741b010.png)

None of the games from itch have their icons downloaded.

**Comment by PhilipK** [comment]
I cannot reproduce this in the newest version, can you try 0.9.25 ?

**Comment by PhilipK** [comment]
Reproduced on windows, fix incoming

**Comment by PhilipK** [comment]
Should be fixed in version 1.0.0 (if not, let me know)
