### ISSUE TITLE
New UI is excessively zoomed in on Steam Deck

### ISSUE THREAD

**Issue by Lite2Key** [PhilipK/BoilR#75]
I just grabbed v1.0.0 and opened it, but with the new UI I'm unable to see much, and it's also become hard to scroll.
![16495519900861955391173965829931](https://user-images.githubusercontent.com/16891950/162596617-29b1c14c-2f51-4633-abdd-8727e7f961ca.jpg)

**Comment by PhilipK** [comment]
Sorry about that!
This release should fix the problem (downloads should be ready 7 minutes after i have posted this):
https://github.com/PhilipK/BoilR/releases/tag/v1.0.1

**Comment by PhilipK** [comment]
I assume this is fixed in the newest release, so will close this issue. If it is still there, please post here again and I will reopen the issue.
