### ISSUE TITLE
fixed Version Tag Format 

### ISSUE THREAD

**Issue by jrtberlin** [PhilipK/BoilR#76]
Please use a fixed format for version tags on the repo. 
Currently it seems to alternative between `v.x.x.x` and `vx.x.x`.

**Comment by PhilipK** [comment]
Roger, currently it is a manual process to define the version number, I
made a mistake.

Is this for something that is being automated?

Do you need me to do another release that has a specific version name?

**Comment by jrtberlin** [comment]
Its party automated in the AUR package, but would make the URLs and archive names predictable for other packagers. 
I don't need a new release. I adjusted in manually in the PKGBUILD.

**Comment by PhilipK** [comment]
I will stick to v.x.x.x in the future
