### ISSUE TITLE
Add support for Amazon Gaming

### ISSUE THREAD

**Issue by Justin27482** [PhilipK/BoilR#77]
Prime provides free games every month, but most of them use the Amazon launcher.  It would be great to be able to add these games to Steam.

**Comment by Untz64** [comment]
Started looking into what this would take. On Windows, the file `%localappdata%\Amazon Games\Data\Games\Sql\GameInstallInfo.sqlite` looks to include some of the necessary data (`InstallDirectory` and ` ProductTitle`) BoilR would need to scrape for, though I have no idea how to interact with sqlite DB's with Rust. Of note, the `InstallDirectory` table is just the path, it does not include the executable for the game.

**Comment by PhilipK** [comment]
There are libraries for interacting with sqllite from rust  https://crates.io/crates/sqlite
The id that is needed for the url, did you find that in the DB?
I guess if we have the ID and the name we are good

**Comment by Untz64** [comment]
Yes, there's really just one table with data, and it has the 'ID' and 'ProductTitle' as columns. I tried to put something together last night using `sqlite_parser` but I have virtually no experience in Rust

**Comment by PhilipK** [comment]
Awesome that all the data is so easily available, good job finding that.
Should be easy to make an integration now.
Can't promise anything but I will try to get this working for windows this week. Linux might be interesting.

**Comment by PhilipK** [comment]
Amazon Game support for windows is now available in the newest release:
https://github.com/PhilipK/BoilR/releases/tag/v.1.1.0
