### ISSUE TITLE
Steam deck : games not running

### ISSUE THREAD

**Issue by ReyAnthony** [PhilipK/BoilR#81]
Using heroic : 

- Cyberpunk (GOG) seems to be running (I hear the game audio), but stays in background and steamdeck ui will not hide ! (Works on desktop mode !) 

- Sonic Mania (Epic) - will not run (please lauch with epic game launcher popup) 
- FF7 remake (Epic) same issue, will not run

Don't know if Sonic and FF7 are fixable ? 
The launcher should run them, but I don't know if heroic supports any kind of launch url scheme to try and bypass this.

Those game run when launched from Heroic GUI

**Comment by ReyAnthony** [comment]
Partly related to https://github.com/PhilipK/BoilR/issues/13

**Comment by PhilipK** [comment]
There must be something that BoilR does not add to the shortcuts that Heroic does. It should be easier to fix once I get a steam deck.

**Comment by jrtberlin** [comment]
I have the same issue with The Witcher 3 GOTY Edition from GOG.

**Comment by PhilipK** [comment]
In version https://github.com/PhilipK/BoilR/releases/tag/v.1.3.9 I have added an option to launch games through Heroic, it should fix this issue. I assume it is fixed, but if it is not, let me know and I will re-open this issue.
