### ISSUE TITLE
SteamGridDB API 100 games limit

### ISSUE THREAD

**Issue by Untz64** [PhilipK/BoilR#86]
Getting the following error when trying to grab images: 

```
Checking for game images
Error getting images: Image search failed SteamGridDbError { status: None, errors: Some(["You cannot request more than 100 games at a time."]) }
```

I'm not sure if the limit is 100 games in one query, or if there's a time out value associated with the API key. Assuming the former, would it be possible to perform the query in batches?

**Comment by PhilipK** [comment]
Yes, thanks for reporting this!
Should be easy to download in batches, I will look at it asap.
For now you can try to deselect some games, import the rest and then import them all.
It does not download games that it already has art for.

**Comment by PhilipK** [comment]
This should be fixed in https://github.com/PhilipK/BoilR/releases/tag/v.1.0.8 if not, then let me know and I will reopen this issue.

**Comment by Untz64** [comment]
I'm doing some testing now, but initial results weren't great lol. I'm not sure exactly what happened, but the first run definitely did the API request properly, but it didn't apply images to most of the library (~220 shortcuts), and the ones it did grab got mixed around. Second run was completely fine though

**Comment by PhilipK** [comment]
I will try to recreate by artificially setting the limit to 5 and see what happens on my own machines.
Which OS is this on?

**Comment by Untz64** [comment]
Windows 10. I have a hunch that this is a separate bug, since BoilR grabs images for all shortcuts in shortcuts.vdf, and I had several other shortcuts that weren't added by BoilR before removing my grid folder to test.

**Comment by Untz64** [comment]
Alright, so a few things I've figured out:

- I'm almost positive my old `shortcuts.vdf` had something BoilR didn't like; I didn't have any mixed up images when BoilR made that file from scratch.
- If there's more than one steam user folder in `userdata`, images are only being placed in the last folder. Tested it by making a blank `New Folder` directory; shorcuts.vdf was created in both, but grid folder was only populated in `New Folder`. Maybe this is what's going on with #87 ?

But, the original issue itself is absolutely fixed.

**Comment by PhilipK** [comment]
About multiple users.
If you have actual multiple users (like I have) it will download images for both, it has been verified by others (in older issues).
I don't think that is what is going on.

If you ever experience it again I would be very interested to see your shortcut file, to figure out what is wrong. I have seen other tools do stuff to the shortcut file that steam would never do to it, but steam seams to still be able to read it, but BoilR did not expect that format.
