### ISSUE TITLE
Some times downloaded images are size 0

### ISSUE THREAD

**Issue by marcodallagatta** [PhilipK/BoilR#87]
Hello, using BoilR 1.0.7 on Steam Deck I've noticed that some games' "poster artworks" are not downloaded, specifically, all from EGS (via Heroic): ABZU, Alien: Isolation, Into The Breach, Salt and Sanctuary and A Short Hike.

If I enter the game I can see the wide artwork, but in the "collection" view I cannot see the tall rectangular one. For example, for ABZU I don't see [this](https://www.steamgriddb.com/grid/41413), but I see [this one](https://www.steamgriddb.com/hero/8688) when I enter the dedicated page.

All of these get recognized in the GUI.

**Comment by PhilipK** [comment]
Interesting, I have some of those games and have tried to install then with Heroic (but not on a Deck since I don't have one) and it works here [yes yes, i know, works on my machine]. Can you check your grid folder?
In your steams grid folder,  /home/deck/.steam/userdata/xxxxxx/config/grid where xxxx is your userid, are the poster images downloaded?

**Comment by marcodallagatta** [comment]
I don't know if you just forgot a "steam" but the path is slightly different, it's /home/deck/.steam/**steam**/userdata/xxx/config/grid (not saying this to be pedantic, but maybe the folder structure is different on the Deck and you weren't aware).

In that folder there are the artworks I see, and for the games that don't display them a 0 B .png file with the same numeric filename. For example the ABZU wide artwork is named 2838916372_hero.png, there's also a 2838916372_bigpicture, 2838916372_logo, and an 2838916372.ico, but then there's an empty files: 2838916372p.png.

So... I delete all the empty file, ran BoilR again, and now everything works 🤔 I don't know what to say... I don't really have a clue about what might have caused the issue in the first place. I can only think about doing a filesize check before applying the picture?

Btw I don't know if this is intended or not (either way it's perfect), but BoilR is also downloading artwork for other non-steam apps such as Chrome or Firefox 🙏

**Comment by PhilipK** [comment]
I guess a workaround is for BoilR to check if the downloaded file is the wrong size, if it is, then delete it. On next import it should be downloaded then.

Ofc this could be automated, but I am just worried about making infinite loops.

**Comment by PhilipK** [comment]
@marcodallagatta since it is now possible so change an incorrect image from Boilr I think I will let users manually handle this in the rare case that it happens. I fear that he added complexity, of guessing if a download was wrong, will just lead to other bugs down the line.
What do you think?

**Comment by marcodallagatta** [comment]
Of course. Maybe just a simple check that deletes the 0 bytes files after the whole process is done? That way they would be downloaded again at the next run, where if those files are present BoilR would just skip re-downloading them as far as I understand it.

**Comment by marcodallagatta** [comment]
Thank you Philip 🙏
