### ISSUE TITLE
Feature request: change name of imported game

### ISSUE THREAD

**Issue by Untz64** [PhilipK/BoilR#89]
Sometimes the scraped name of games isn't accurate or pretty (i.e. trademark symbol, missing spaces). It's simple enough to rename in Steam after importing, but it would be nice to be able to change it within BoilR. It might also fix issues with searching for games on SteamGridDB, though I haven't personally encountered issues with that.

**Comment by PhilipK** [comment]
I guess this is possible by making an "rename map" from appid to new name. This will change the actual appid for the new game, but it will happen consistently.

For the UI what do you think would be the best? An seperate section in the settings with "renames" hidden behind a fold?

**Comment by Untz64** [comment]
I'm not sure how difficult it would be, but for UI I was thinking of changing them directly on the `Import Games` window, like via right click -> rename. Thoughts?

**Comment by PhilipK** [comment]
Right click rename is a good idea. Does not clutter the UI. I constantly forget that this is not web, and right-click is an option.

**Comment by PhilipK** [comment]
This will be in the next release
