### ISSUE TITLE
Library icons for non-Steam games deleted after import

### ISSUE THREAD

**Issue by jayareemcee** [PhilipK/BoilR#90]
All settings are default, except the `Download Images` option, which is enabled, as well as `Stop/Start Steam`. No games imported - only utilizing the app to automatically download banners and the sort. Icons, unfortunately, break during the process.

**Comment by PhilipK** [comment]
So BoilR removes the icons for games that already have them?

**Comment by jayareemcee** [comment]
> So BoilR removes the icons for games that already have them?

Aye, that about sums it up.

**Comment by PhilipK** [comment]
Found the bug, it will be fixed in the next release.

Fixed in this commit:
https://github.com/PhilipK/BoilR/commit/521eb54cbb951c86550586cb65b1e7c0e0950d92
