### ISSUE TITLE
Flatpak Lutris Games are not Found

### ISSUE THREAD

**Issue by NightHammer1000** [PhilipK/BoilR#96]
If you have the Flatpak Version of Lutris installed, the Games are not found.

Also a option to Import the Games Direct Path into Steam and not the Lutris Launch Action would be nice

**Comment by PhilipK** [comment]
Confirmed not working.
I don't think that there was a Flatpak version back when I originally made the lutris integration.
It is most likely a matter of just finding out where lutris installed when it is not on path.

About the "direct path" I have not looked into how that would work? I don't know if lutris can tell us where it installed its games

**Comment by NightHammer1000** [comment]
On the Steam Deck its under /home/deck/.var/app/net.lutris.Lutris/

in there is config/lutris/games

In there are yml files that contain all the Infos for each Game.
Including the Direct Path to the Games Executeable.

**Comment by NightHammer1000** [comment]
FYI, newest Lutris Flatpak Version has a option to add Steam Shortcuts for its Games.
But still very simple. Without Icons or Images.

**Comment by PhilipK** [comment]
Thanks for update.
Good Lutris has the option now! Could end up being a better experience for gamers in the long run, which is the goal with BoilR.

**Comment by NightHammer1000** [comment]
Yeah. I think so too. I hope they fix the Icon and Banner Import.
I got spoiled by SteamGridDB on Windows with Playnite and wont miss it now^^

**Comment by cherokee93** [comment]
> Thanks for update. Good Lutris has the option now! Could end up being a better experience for gamers in the long run, which is the goal with BoilR.

I see BoilR updates all the art of non-steam games so it's still helping with games added by lutris😂 I'd prefer for games to be detected by BoilR, and hope some day they will (same with windows itch.io games)

**Comment by PhilipK** [comment]
@NightHammer1000 have you tried changing the "lutris executable" setting to point it to the one installed with flatpak?
Should be in  /home/deck/.var/app/net.lutris.Lutris/ somewhere.
I am having trouble installing Lutris through the flatpak on my Arch installation, might have to dig out an old laptop and install Manjaro with KDE to really test this.

**Comment by NightHammer1000** [comment]
Yeah. Tried that. Did not work out.

**Comment by PhilipK** [comment]
This should be solved in the next version of BoilR

**Comment by PhilipK** [comment]
This is in the newest release, @NightHammer1000  let me know if it doesn't work for you, then I will reopen this issue.

**Comment by NightHammer1000** [comment]
works!

**Comment by zaubara** [comment]
Doesn’t seem to work on the Steam Deck, sadly. I tried different viable settings, none seemed to work.

**Comment by cherokee93** [comment]
> Doesn’t seem to work on the Steam Deck, sadly. I tried different viable settings, none seemed to work.

Try the linux executable version, the flatpak one doesn't work well for me but the other version detects everything

**Comment by NightHammer1000** [comment]
Somehow. My Lutris Games are only detected when Lutris itself is closed. So keep that in mind.
